var annotated =
[
    [ "_INTAT", "union___i_n_t_a_t.html", "union___i_n_t_a_t" ],
    [ "_PCLKSEL0", "union___p_c_l_k_s_e_l0.html", "union___p_c_l_k_s_e_l0" ],
    [ "_PCLKSEL1", "union___p_c_l_k_s_e_l1.html", "union___p_c_l_k_s_e_l1" ],
    [ "_PCONP", "union___p_c_o_n_p.html", "union___p_c_o_n_p" ],
    [ "_TxCCR", "struct___tx_c_c_r.html", "struct___tx_c_c_r" ],
    [ "_TxCTCR", "struct___tx_c_t_c_r.html", "struct___tx_c_t_c_r" ],
    [ "_TxEMR", "struct___tx_e_m_r.html", "struct___tx_e_m_r" ],
    [ "_TxIR", "struct___tx_i_r.html", "struct___tx_i_r" ],
    [ "_TxMCR", "union___tx_m_c_r.html", "union___tx_m_c_r" ],
    [ "_TxTCR", "struct___tx_t_c_r.html", "struct___tx_t_c_r" ],
    [ "AbortContext", "struct_abort_context.html", "struct_abort_context" ],
    [ "xpcc::AbstractComponent", "classxpcc_1_1_abstract_component.html", "classxpcc_1_1_abstract_component" ],
    [ "xpcc::amnb::Action", "structxpcc_1_1amnb_1_1_action.html", "structxpcc_1_1amnb_1_1_action" ],
    [ "xpcc::sab::Action", "structxpcc_1_1sab_1_1_action.html", "structxpcc_1_1sab_1_1_action" ],
    [ "xpcc::ActionCallback", "classxpcc_1_1_action_callback.html", "classxpcc_1_1_action_callback" ],
    [ "xpcc::Ad7280a< Spi, Cs, Cnvst, N >", "classxpcc_1_1_ad7280a.html", "classxpcc_1_1_ad7280a" ],
    [ "xpcc::AD840x< Spi, Cs, Rs, Shdn >", "classxpcc_1_1_a_d840x.html", "classxpcc_1_1_a_d840x" ],
    [ "xpcc::at91::Adc", "classxpcc_1_1at91_1_1_adc.html", "classxpcc_1_1at91_1_1_adc" ],
    [ "xpcc::atmega::Adc", "classxpcc_1_1atmega_1_1_adc.html", "classxpcc_1_1atmega_1_1_adc" ],
    [ "xpcc::stm32::Adc1", "classxpcc_1_1stm32_1_1_adc1.html", "classxpcc_1_1stm32_1_1_adc1" ],
    [ "xpcc::stm32::Adc2", "classxpcc_1_1stm32_1_1_adc2.html", "classxpcc_1_1stm32_1_1_adc2" ],
    [ "xpcc::stm32::Adc3", "classxpcc_1_1stm32_1_1_adc3.html", "classxpcc_1_1stm32_1_1_adc3" ],
    [ "xpcc::atxmega::AdcA", "classxpcc_1_1atxmega_1_1_adc_a.html", "classxpcc_1_1atxmega_1_1_adc_a" ],
    [ "xpcc::atxmega::AdcB", "classxpcc_1_1atxmega_1_1_adc_b.html", "classxpcc_1_1atxmega_1_1_adc_b" ],
    [ "xpcc::atxmega::AdcChannelA0", "classxpcc_1_1atxmega_1_1_adc_channel_a0.html", "classxpcc_1_1atxmega_1_1_adc_channel_a0" ],
    [ "xpcc::atxmega::AdcChannelA1", "classxpcc_1_1atxmega_1_1_adc_channel_a1.html", "classxpcc_1_1atxmega_1_1_adc_channel_a1" ],
    [ "xpcc::atxmega::AdcChannelA2", "classxpcc_1_1atxmega_1_1_adc_channel_a2.html", "classxpcc_1_1atxmega_1_1_adc_channel_a2" ],
    [ "xpcc::atxmega::AdcChannelA3", "classxpcc_1_1atxmega_1_1_adc_channel_a3.html", "classxpcc_1_1atxmega_1_1_adc_channel_a3" ],
    [ "xpcc::atxmega::AdcChannelB0", "classxpcc_1_1atxmega_1_1_adc_channel_b0.html", "classxpcc_1_1atxmega_1_1_adc_channel_b0" ],
    [ "xpcc::atxmega::AdcChannelB1", "classxpcc_1_1atxmega_1_1_adc_channel_b1.html", "classxpcc_1_1atxmega_1_1_adc_channel_b1" ],
    [ "xpcc::atxmega::AdcChannelB2", "classxpcc_1_1atxmega_1_1_adc_channel_b2.html", "classxpcc_1_1atxmega_1_1_adc_channel_b2" ],
    [ "xpcc::atxmega::AdcChannelB3", "classxpcc_1_1atxmega_1_1_adc_channel_b3.html", "classxpcc_1_1atxmega_1_1_adc_channel_b3" ],
    [ "xpcc::atmega::AdcInterrupt", "classxpcc_1_1atmega_1_1_adc_interrupt.html", "classxpcc_1_1atmega_1_1_adc_interrupt" ],
    [ "xpcc::stm32::AdvancedControlTimer", "classxpcc_1_1stm32_1_1_advanced_control_timer.html", "classxpcc_1_1stm32_1_1_advanced_control_timer" ],
    [ "xpcc::Adxl345< I2cMaster >", "classxpcc_1_1_adxl345.html", "classxpcc_1_1_adxl345" ],
    [ "xpcc::at91::Aic", "classxpcc_1_1at91_1_1_aic.html", "classxpcc_1_1at91_1_1_aic" ],
    [ "xpcc::allocator::AllocatorBase< T >", "classxpcc_1_1allocator_1_1_allocator_base.html", "classxpcc_1_1allocator_1_1_allocator_base" ],
    [ "xpcc::stm32::AlternateMode< P, N, bool >", "structxpcc_1_1stm32_1_1_alternate_mode.html", "structxpcc_1_1stm32_1_1_alternate_mode" ],
    [ "xpcc::stm32::AlternateMode< P, N, false >", "structxpcc_1_1stm32_1_1_alternate_mode_3_01_p_00_01_n_00_01false_01_4.html", "structxpcc_1_1stm32_1_1_alternate_mode_3_01_p_00_01_n_00_01false_01_4" ],
    [ "xpcc::atmega::AnalogSensors< ADConv, CHANNELS, SAMPLES >", "classxpcc_1_1atmega_1_1_analog_sensors.html", "classxpcc_1_1atmega_1_1_analog_sensors" ],
    [ "xpcc::Angle", "classxpcc_1_1_angle.html", "classxpcc_1_1_angle" ],
    [ "xpcc::ArithmeticTraits< T >", "structxpcc_1_1_arithmetic_traits.html", null ],
    [ "xpcc::ArithmeticTraits< char >", "structxpcc_1_1_arithmetic_traits_3_01char_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01char_01_4" ],
    [ "xpcc::ArithmeticTraits< double >", "structxpcc_1_1_arithmetic_traits_3_01double_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01double_01_4" ],
    [ "xpcc::ArithmeticTraits< float >", "structxpcc_1_1_arithmetic_traits_3_01float_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01float_01_4" ],
    [ "xpcc::ArithmeticTraits< int16_t >", "structxpcc_1_1_arithmetic_traits_3_01int16__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01int16__t_01_4" ],
    [ "xpcc::ArithmeticTraits< int32_t >", "structxpcc_1_1_arithmetic_traits_3_01int32__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01int32__t_01_4" ],
    [ "xpcc::ArithmeticTraits< int64_t >", "structxpcc_1_1_arithmetic_traits_3_01int64__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01int64__t_01_4" ],
    [ "xpcc::ArithmeticTraits< signed char >", "structxpcc_1_1_arithmetic_traits_3_01signed_01char_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01signed_01char_01_4" ],
    [ "xpcc::ArithmeticTraits< uint16_t >", "structxpcc_1_1_arithmetic_traits_3_01uint16__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01uint16__t_01_4" ],
    [ "xpcc::ArithmeticTraits< uint32_t >", "structxpcc_1_1_arithmetic_traits_3_01uint32__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01uint32__t_01_4" ],
    [ "xpcc::ArithmeticTraits< uint64_t >", "structxpcc_1_1_arithmetic_traits_3_01uint64__t_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01uint64__t_01_4" ],
    [ "xpcc::ArithmeticTraits< unsigned char >", "structxpcc_1_1_arithmetic_traits_3_01unsigned_01char_01_4.html", "structxpcc_1_1_arithmetic_traits_3_01unsigned_01char_01_4" ],
    [ "xpcc::At45db0x1d< Spi, Cs >", "classxpcc_1_1_at45db0x1d.html", "classxpcc_1_1_at45db0x1d" ],
    [ "xpcc::BackendInterface", "classxpcc_1_1_backend_interface.html", "classxpcc_1_1_backend_interface" ],
    [ "xpcc::stm32::BasicTimer", "classxpcc_1_1stm32_1_1_basic_timer.html", "classxpcc_1_1stm32_1_1_basic_timer" ],
    [ "xpcc::rtos::BinarySemaphore", "classxpcc_1_1rtos_1_1_binary_semaphore.html", "classxpcc_1_1rtos_1_1_binary_semaphore" ],
    [ "xpcc::allocator::Block< T, BLOCKSIZE >", "classxpcc_1_1allocator_1_1_block.html", "classxpcc_1_1allocator_1_1_block" ],
    [ "xpcc::Bma180< I2cMaster >", "classxpcc_1_1_bma180.html", "classxpcc_1_1_bma180" ],
    [ "xpcc::Bmp085< I2cMaster >", "classxpcc_1_1_bmp085.html", "classxpcc_1_1_bmp085" ],
    [ "xpcc::BoundedDeque< T, N >", "classxpcc_1_1_bounded_deque.html", "classxpcc_1_1_bounded_deque" ],
    [ "xpcc::BoundedQueue< T, N, Container >", "classxpcc_1_1_bounded_queue.html", "classxpcc_1_1_bounded_queue" ],
    [ "xpcc::BoundedStack< T, N, Container >", "classxpcc_1_1_bounded_stack.html", "classxpcc_1_1_bounded_stack" ],
    [ "xpcc::BufferedGraphicDisplay< Width, Height >", "classxpcc_1_1_buffered_graphic_display.html", "classxpcc_1_1_buffered_graphic_display" ],
    [ "xpcc::atmega::BufferedUart0", "classxpcc_1_1atmega_1_1_buffered_uart0.html", "classxpcc_1_1atmega_1_1_buffered_uart0" ],
    [ "xpcc::atmega::BufferedUart1", "classxpcc_1_1atmega_1_1_buffered_uart1.html", "classxpcc_1_1atmega_1_1_buffered_uart1" ],
    [ "xpcc::atmega::BufferedUart2", "classxpcc_1_1atmega_1_1_buffered_uart2.html", "classxpcc_1_1atmega_1_1_buffered_uart2" ],
    [ "xpcc::atmega::BufferedUart3", "classxpcc_1_1atmega_1_1_buffered_uart3.html", "classxpcc_1_1atmega_1_1_buffered_uart3" ],
    [ "xpcc::stm32::BufferedUart4", "classxpcc_1_1stm32_1_1_buffered_uart4.html", "classxpcc_1_1stm32_1_1_buffered_uart4" ],
    [ "xpcc::stm32::BufferedUart5", "classxpcc_1_1stm32_1_1_buffered_uart5.html", "classxpcc_1_1stm32_1_1_buffered_uart5" ],
    [ "xpcc::stm32::BufferedUsart1", "classxpcc_1_1stm32_1_1_buffered_usart1.html", "classxpcc_1_1stm32_1_1_buffered_usart1" ],
    [ "xpcc::stm32::BufferedUsart2", "classxpcc_1_1stm32_1_1_buffered_usart2.html", "classxpcc_1_1stm32_1_1_buffered_usart2" ],
    [ "xpcc::stm32::BufferedUsart3", "classxpcc_1_1stm32_1_1_buffered_usart3.html", "classxpcc_1_1stm32_1_1_buffered_usart3" ],
    [ "xpcc::stm32::BufferedUsart6", "classxpcc_1_1stm32_1_1_buffered_usart6.html", "classxpcc_1_1stm32_1_1_buffered_usart6" ],
    [ "xpcc::Button< PIN >", "classxpcc_1_1_button.html", "classxpcc_1_1_button" ],
    [ "xpcc::ButtonGroup< T >", "classxpcc_1_1_button_group.html", "classxpcc_1_1_button_group" ],
    [ "xpcc::amnb::Callable", "structxpcc_1_1amnb_1_1_callable.html", null ],
    [ "xpcc::sab::Callable", "structxpcc_1_1sab_1_1_callable.html", null ],
    [ "xpcc::stm32::Can1", "classxpcc_1_1stm32_1_1_can1.html", "classxpcc_1_1stm32_1_1_can1" ],
    [ "xpcc::CanConnector< Driver >", "classxpcc_1_1_can_connector.html", "classxpcc_1_1_can_connector" ],
    [ "xpcc::CanConnectorBase", "classxpcc_1_1_can_connector_base.html", "classxpcc_1_1_can_connector_base" ],
    [ "xpcc::stm32::CanFilter", "classxpcc_1_1stm32_1_1_can_filter.html", "classxpcc_1_1stm32_1_1_can_filter" ],
    [ "xpcc::CanLawicelFormatter", "classxpcc_1_1_can_lawicel_formatter.html", "classxpcc_1_1_can_lawicel_formatter" ],
    [ "xpcc::CanUsb", "classxpcc_1_1_can_usb.html", "classxpcc_1_1_can_usb" ],
    [ "xpcc::CharacterDisplay", "classxpcc_1_1_character_display.html", "classxpcc_1_1_character_display" ],
    [ "xpcc::Circle2D< T >", "classxpcc_1_1_circle2_d.html", "classxpcc_1_1_circle2_d" ],
    [ "xpcc::stm32::Clock", "classxpcc_1_1stm32_1_1_clock.html", "classxpcc_1_1stm32_1_1_clock" ],
    [ "xpcc::lpc::Clock", "classxpcc_1_1lpc_1_1_clock.html", null ],
    [ "xpcc::amnb::Clock", "classxpcc_1_1amnb_1_1_clock.html", "classxpcc_1_1amnb_1_1_clock" ],
    [ "xpcc::Clock", "classxpcc_1_1_clock.html", "classxpcc_1_1_clock" ],
    [ "xpcc::Communicatable", "classxpcc_1_1_communicatable.html", null ],
    [ "xpcc::CommunicatableTask", "classxpcc_1_1_communicatable_task.html", "classxpcc_1_1_communicatable_task" ],
    [ "xpcc::Communicator", "classxpcc_1_1_communicator.html", "classxpcc_1_1_communicator" ],
    [ "xpcc::BoundedDeque< T, N >::const_iterator", "classxpcc_1_1_bounded_deque_1_1const__iterator.html", "classxpcc_1_1_bounded_deque_1_1const__iterator" ],
    [ "xpcc::DoublyLinkedList< T, Allocator >::const_iterator", "classxpcc_1_1_doubly_linked_list_1_1const__iterator.html", "classxpcc_1_1_doubly_linked_list_1_1const__iterator" ],
    [ "xpcc::DynamicArray< T, Allocator >::const_iterator", "classxpcc_1_1_dynamic_array_1_1const__iterator.html", "classxpcc_1_1_dynamic_array_1_1const__iterator" ],
    [ "xpcc::LinkedList< T, Allocator >::const_iterator", "classxpcc_1_1_linked_list_1_1const__iterator.html", "classxpcc_1_1_linked_list_1_1const__iterator" ],
    [ "xpcc::atomic::Container< T >", "classxpcc_1_1atomic_1_1_container.html", "classxpcc_1_1atomic_1_1_container" ],
    [ "unittest::Controller", "classunittest_1_1_controller.html", "classunittest_1_1_controller" ],
    [ "xpcc::tmp::Conversion< T, U >", "classxpcc_1_1tmp_1_1_conversion.html", null ],
    [ "xpcc::tmp::Conversion< T, T >", "structxpcc_1_1tmp_1_1_conversion_3_01_t_00_01_t_01_4.html", null ],
    [ "xpcc::tmp::Conversion< T, void >", "structxpcc_1_1tmp_1_1_conversion_3_01_t_00_01void_01_4.html", null ],
    [ "xpcc::tmp::Conversion< void, T >", "structxpcc_1_1tmp_1_1_conversion_3_01void_00_01_t_01_4.html", null ],
    [ "xpcc::tmp::Conversion< void, void >", "structxpcc_1_1tmp_1_1_conversion_3_01void_00_01void_01_4.html", null ],
    [ "xpcc::ad7280a::ConversionValue", "structxpcc_1_1ad7280a_1_1_conversion_value.html", "structxpcc_1_1ad7280a_1_1_conversion_value" ],
    [ "xpcc::stm32::Core", "classxpcc_1_1stm32_1_1_core.html", "classxpcc_1_1stm32_1_1_core" ],
    [ "xpcc::at91::Core", "classxpcc_1_1at91_1_1_core.html", null ],
    [ "unittest::CountType", "classunittest_1_1_count_type.html", "classunittest_1_1_count_type" ],
    [ "xpcc::CpuBoard2< Transmit, Receive >", "classxpcc_1_1_cpu_board2.html", "classxpcc_1_1_cpu_board2" ],
    [ "xpcc::CpuBoard2Slave< Transmit, Receive >", "classxpcc_1_1_cpu_board2_slave.html", "classxpcc_1_1_cpu_board2_slave" ],
    [ "xpcc::Date", "classxpcc_1_1_date.html", "classxpcc_1_1_date" ],
    [ "xpcc::filter::Debounce< T >", "classxpcc_1_1filter_1_1_debounce.html", "classxpcc_1_1filter_1_1_debounce" ],
    [ "xpcc::at91::Debug", "classxpcc_1_1at91_1_1_debug.html", "classxpcc_1_1at91_1_1_debug" ],
    [ "xpcc::log::DefaultStyle", "classxpcc_1_1log_1_1_default_style.html", "classxpcc_1_1log_1_1_default_style" ],
    [ "xpcc::i2c::Delegate", "classxpcc_1_1i2c_1_1_delegate.html", "classxpcc_1_1i2c_1_1_delegate" ],
    [ "xpcc::fat::Directory", "classxpcc_1_1fat_1_1_directory.html", "classxpcc_1_1fat_1_1_directory" ],
    [ "xpcc::Dispatcher", "classxpcc_1_1_dispatcher.html", "classxpcc_1_1_dispatcher" ],
    [ "xpcc::atxmega::DmaChannel0", "classxpcc_1_1atxmega_1_1_dma_channel0.html", "classxpcc_1_1atxmega_1_1_dma_channel0" ],
    [ "xpcc::atxmega::DmaChannel1", "classxpcc_1_1atxmega_1_1_dma_channel1.html", "classxpcc_1_1atxmega_1_1_dma_channel1" ],
    [ "xpcc::atxmega::DmaChannel2", "classxpcc_1_1atxmega_1_1_dma_channel2.html", "classxpcc_1_1atxmega_1_1_dma_channel2" ],
    [ "xpcc::atxmega::DmaChannel3", "classxpcc_1_1atxmega_1_1_dma_channel3.html", "classxpcc_1_1atxmega_1_1_dma_channel3" ],
    [ "xpcc::atxmega::DmaController", "classxpcc_1_1atxmega_1_1_dma_controller.html", "classxpcc_1_1atxmega_1_1_dma_controller" ],
    [ "xpcc::DogL128< SPI, CS, A0, Reset, TopView >", "classxpcc_1_1_dog_l128.html", "classxpcc_1_1_dog_l128" ],
    [ "xpcc::DogM081< SPI, CS, RS >", "classxpcc_1_1_dog_m081.html", "classxpcc_1_1_dog_m081" ],
    [ "xpcc::DogM128< SPI, CS, A0, Reset, TopView >", "classxpcc_1_1_dog_m128.html", "classxpcc_1_1_dog_m128" ],
    [ "xpcc::DogM132< SPI, CS, A0, Reset, TopView >", "classxpcc_1_1_dog_m132.html", "classxpcc_1_1_dog_m132" ],
    [ "xpcc::DogM162< SPI, CS, RS >", "classxpcc_1_1_dog_m162.html", "classxpcc_1_1_dog_m162" ],
    [ "xpcc::DogM163< SPI, CS, RS >", "classxpcc_1_1_dog_m163.html", "classxpcc_1_1_dog_m163" ],
    [ "xpcc::DogS102< SPI, CS, A0, Reset, TopView >", "classxpcc_1_1_dog_s102.html", "classxpcc_1_1_dog_s102" ],
    [ "xpcc::led::DoubleIndicator< LedClass >", "classxpcc_1_1led_1_1_double_indicator.html", "classxpcc_1_1led_1_1_double_indicator" ],
    [ "xpcc::DoublyLinkedList< T, Allocator >", "classxpcc_1_1_doubly_linked_list.html", "classxpcc_1_1_doubly_linked_list" ],
    [ "xpcc::Ds1631< I2cMaster >", "classxpcc_1_1_ds1631.html", "classxpcc_1_1_ds1631" ],
    [ "xpcc::Ds18b20< OneWire >", "classxpcc_1_1_ds18b20.html", "classxpcc_1_1_ds18b20" ],
    [ "xpcc::allocator::Dynamic< T >", "classxpcc_1_1allocator_1_1_dynamic.html", "classxpcc_1_1allocator_1_1_dynamic" ],
    [ "xpcc::DynamicArray< T, Allocator >", "classxpcc_1_1_dynamic_array.html", "classxpcc_1_1_dynamic_array" ],
    [ "xpcc::DynamicPostman", "classxpcc_1_1_dynamic_postman.html", "classxpcc_1_1_dynamic_postman" ],
    [ "xpcc::Empty", "structxpcc_1_1_empty.html", null ],
    [ "xpcc::tmp::EnableIf< Conditional, T >", "structxpcc_1_1tmp_1_1_enable_if.html", "structxpcc_1_1tmp_1_1_enable_if" ],
    [ "xpcc::tmp::EnableIfCondition< B, T >", "structxpcc_1_1tmp_1_1_enable_if_condition.html", "structxpcc_1_1tmp_1_1_enable_if_condition" ],
    [ "xpcc::tmp::EnableIfCondition< false, T >", "structxpcc_1_1tmp_1_1_enable_if_condition_3_01false_00_01_t_01_4.html", null ],
    [ "xpcc::amnb::ErrorHandler", "structxpcc_1_1amnb_1_1_error_handler.html", "structxpcc_1_1amnb_1_1_error_handler" ],
    [ "xpcc::ErrorReport", "classxpcc_1_1_error_report.html", "classxpcc_1_1_error_report" ],
    [ "xpcc::stm32::CanFilter::ExtendedFilterMask", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_filter_mask.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_filter_mask" ],
    [ "xpcc::stm32::CanFilter::ExtendedFilterMaskShort", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_filter_mask_short.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_filter_mask_short" ],
    [ "xpcc::stm32::CanFilter::ExtendedIdentifier", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_identifier.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_identifier" ],
    [ "xpcc::stm32::CanFilter::ExtendedIdentifierShort", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_identifier_short.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_extended_identifier_short" ],
    [ "xpcc::fat::File", "classxpcc_1_1fat_1_1_file.html", "classxpcc_1_1fat_1_1_file" ],
    [ "xpcc::fat::FileInfo", "classxpcc_1_1fat_1_1_file_info.html", "classxpcc_1_1fat_1_1_file_info" ],
    [ "xpcc::fat::FileSystem", "classxpcc_1_1fat_1_1_file_system.html", "classxpcc_1_1fat_1_1_file_system" ],
    [ "xpcc::atomic::Flag", "classxpcc_1_1atomic_1_1_flag.html", "classxpcc_1_1atomic_1_1_flag" ],
    [ "xpcc::can::Message::Flags", "structxpcc_1_1can_1_1_message_1_1_flags.html", "structxpcc_1_1can_1_1_message_1_1_flags" ],
    [ "xpcc::at91::Flash", "classxpcc_1_1at91_1_1_flash.html", null ],
    [ "xpcc::accessor::Flash< T >", "classxpcc_1_1accessor_1_1_flash.html", "classxpcc_1_1accessor_1_1_flash" ],
    [ "xpcc::Ft245< PORT, RD, WR, RXF, TXE >", "classxpcc_1_1_ft245.html", "classxpcc_1_1_ft245" ],
    [ "xpcc::stm32::GeneralPurposeTimer", "classxpcc_1_1stm32_1_1_general_purpose_timer.html", "classxpcc_1_1stm32_1_1_general_purpose_timer" ],
    [ "xpcc::GeometricTraits< T >", "structxpcc_1_1_geometric_traits.html", "structxpcc_1_1_geometric_traits" ],
    [ "xpcc::GeometricTraits< double >", "structxpcc_1_1_geometric_traits_3_01double_01_4.html", "structxpcc_1_1_geometric_traits_3_01double_01_4" ],
    [ "xpcc::GeometricTraits< float >", "structxpcc_1_1_geometric_traits_3_01float_01_4.html", "structxpcc_1_1_geometric_traits_3_01float_01_4" ],
    [ "xpcc::GeometricTraits< int16_t >", "structxpcc_1_1_geometric_traits_3_01int16__t_01_4.html", "structxpcc_1_1_geometric_traits_3_01int16__t_01_4" ],
    [ "xpcc::GeometricTraits< int32_t >", "structxpcc_1_1_geometric_traits_3_01int32__t_01_4.html", "structxpcc_1_1_geometric_traits_3_01int32__t_01_4" ],
    [ "xpcc::GeometricTraits< int8_t >", "structxpcc_1_1_geometric_traits_3_01int8__t_01_4.html", "structxpcc_1_1_geometric_traits_3_01int8__t_01_4" ],
    [ "xpcc::GeometricTraits< uint8_t >", "structxpcc_1_1_geometric_traits_3_01uint8__t_01_4.html", "structxpcc_1_1_geometric_traits_3_01uint8__t_01_4" ],
    [ "xpcc::stm32::GpioMode< P, N, bool >", "structxpcc_1_1stm32_1_1_gpio_mode.html", "structxpcc_1_1stm32_1_1_gpio_mode" ],
    [ "xpcc::stm32::GpioMode< P, N, false >", "structxpcc_1_1stm32_1_1_gpio_mode_3_01_p_00_01_n_00_01false_01_4.html", "structxpcc_1_1stm32_1_1_gpio_mode_3_01_p_00_01_n_00_01false_01_4" ],
    [ "xpcc::GraphicDisplay", "classxpcc_1_1_graphic_display.html", "classxpcc_1_1_graphic_display" ],
    [ "xpcc::Hcla12x5< I2cMaster >", "classxpcc_1_1_hcla12x5.html", "classxpcc_1_1_hcla12x5" ],
    [ "xpcc::Hd44780< E, RW, RS, DATA >", "classxpcc_1_1_hd44780.html", "classxpcc_1_1_hd44780" ],
    [ "xpcc::tipc::Header", "structxpcc_1_1tipc_1_1_header.html", "structxpcc_1_1tipc_1_1_header" ],
    [ "xpcc::Header", "structxpcc_1_1_header.html", "structxpcc_1_1_header" ],
    [ "xpcc::atxmega::HighResC", "classxpcc_1_1atxmega_1_1_high_res_c.html", "classxpcc_1_1atxmega_1_1_high_res_c" ],
    [ "xpcc::atxmega::HighResD", "classxpcc_1_1atxmega_1_1_high_res_d.html", "classxpcc_1_1atxmega_1_1_high_res_d" ],
    [ "xpcc::atxmega::HighResE", "classxpcc_1_1atxmega_1_1_high_res_e.html", "classxpcc_1_1atxmega_1_1_high_res_e" ],
    [ "xpcc::atxmega::HighResF", "classxpcc_1_1atxmega_1_1_high_res_f.html", "classxpcc_1_1atxmega_1_1_high_res_f" ],
    [ "xpcc::Hmc58< I2cMaster >", "classxpcc_1_1_hmc58.html", "classxpcc_1_1_hmc58" ],
    [ "xpcc::Hmc5843< I2cMaster >", "classxpcc_1_1_hmc5843.html", "classxpcc_1_1_hmc5843" ],
    [ "xpcc::Hmc5883l< I2cMaster >", "classxpcc_1_1_hmc5883l.html", "classxpcc_1_1_hmc5883l" ],
    [ "xpcc::color::Hsv", "classxpcc_1_1color_1_1_hsv.html", "classxpcc_1_1color_1_1_hsv" ],
    [ "xpcc::I2cEeprom< I2C >", "classxpcc_1_1_i2c_eeprom.html", "classxpcc_1_1_i2c_eeprom" ],
    [ "xpcc::atmega::I2cMaster", "classxpcc_1_1atmega_1_1_i2c_master.html", "classxpcc_1_1atmega_1_1_i2c_master" ],
    [ "xpcc::stm32::I2cMaster1", "classxpcc_1_1stm32_1_1_i2c_master1.html", "classxpcc_1_1stm32_1_1_i2c_master1" ],
    [ "xpcc::stm32::I2cMaster2", "classxpcc_1_1stm32_1_1_i2c_master2.html", "classxpcc_1_1stm32_1_1_i2c_master2" ],
    [ "xpcc::stm32::I2cMaster3", "classxpcc_1_1stm32_1_1_i2c_master3.html", "classxpcc_1_1stm32_1_1_i2c_master3" ],
    [ "xpcc::atxmega::I2cMasterC", "classxpcc_1_1atxmega_1_1_i2c_master_c.html", "classxpcc_1_1atxmega_1_1_i2c_master_c" ],
    [ "xpcc::atxmega::I2cMasterD", "classxpcc_1_1atxmega_1_1_i2c_master_d.html", "classxpcc_1_1atxmega_1_1_i2c_master_d" ],
    [ "xpcc::atxmega::I2cMasterE", "classxpcc_1_1atxmega_1_1_i2c_master_e.html", "classxpcc_1_1atxmega_1_1_i2c_master_e" ],
    [ "xpcc::atxmega::I2cMasterF", "classxpcc_1_1atxmega_1_1_i2c_master_f.html", "classxpcc_1_1atxmega_1_1_i2c_master_f" ],
    [ "xpcc::led::Indicator< LedClass >", "classxpcc_1_1led_1_1_indicator.html", "classxpcc_1_1led_1_1_indicator" ],
    [ "xpcc::atxmega::InputCapture< TIMER, PIN >", "classxpcc_1_1atxmega_1_1_input_capture.html", "classxpcc_1_1atxmega_1_1_input_capture" ],
    [ "xpcc::InterconnectInterface< T, R >", "classxpcc_1_1_interconnect_interface.html", "classxpcc_1_1_interconnect_interface" ],
    [ "xpcc::InterconnectLink", "structxpcc_1_1_interconnect_link.html", "structxpcc_1_1_interconnect_link" ],
    [ "xpcc::amnb::Interface< Device, PROBABILITY, TIMEOUT >", "classxpcc_1_1amnb_1_1_interface.html", "classxpcc_1_1amnb_1_1_interface" ],
    [ "xpcc::sab::Interface< Device >", "classxpcc_1_1sab_1_1_interface.html", "classxpcc_1_1sab_1_1_interface" ],
    [ "xpcc::sab2::Interface< Device, N >", "classxpcc_1_1sab2_1_1_interface.html", "classxpcc_1_1sab2_1_1_interface" ],
    [ "xpcc::Interface", "classxpcc_1_1_interface.html", null ],
    [ "xpcc::gpio::Invert< Pin >", "classxpcc_1_1gpio_1_1_invert.html", "classxpcc_1_1gpio_1_1_invert" ],
    [ "xpcc::IODevice", "classxpcc_1_1_i_o_device.html", "classxpcc_1_1_i_o_device" ],
    [ "xpcc::IODeviceWrapper< T >", "classxpcc_1_1_i_o_device_wrapper.html", "classxpcc_1_1_i_o_device_wrapper" ],
    [ "xpcc::IOStream", "classxpcc_1_1_i_o_stream.html", "classxpcc_1_1_i_o_stream" ],
    [ "xpcc::DoublyLinkedList< T, Allocator >::iterator", "classxpcc_1_1_doubly_linked_list_1_1iterator.html", "classxpcc_1_1_doubly_linked_list_1_1iterator" ],
    [ "xpcc::DynamicArray< T, Allocator >::iterator", "classxpcc_1_1_dynamic_array_1_1iterator.html", "classxpcc_1_1_dynamic_array_1_1iterator" ],
    [ "xpcc::LinkedList< T, Allocator >::iterator", "classxpcc_1_1_linked_list_1_1iterator.html", "classxpcc_1_1_linked_list_1_1iterator" ],
    [ "xpcc::Itg3200< I2cMaster >", "classxpcc_1_1_itg3200.html", "classxpcc_1_1_itg3200" ],
    [ "xpcc::Ks0108< E, RW, RS, PIN_CS1, PIN_CS2, PORT >", "classxpcc_1_1_ks0108.html", "classxpcc_1_1_ks0108" ],
    [ "xpcc::interpolation::Lagrange< T, Accessor >", "classxpcc_1_1interpolation_1_1_lagrange.html", "classxpcc_1_1interpolation_1_1_lagrange" ],
    [ "xpcc::led::Led", "classxpcc_1_1led_1_1_led.html", "classxpcc_1_1led_1_1_led" ],
    [ "xpcc::Line2D< T >", "classxpcc_1_1_line2_d.html", "classxpcc_1_1_line2_d" ],
    [ "xpcc::interpolation::Linear< T, Accessor >", "classxpcc_1_1interpolation_1_1_linear.html", "classxpcc_1_1interpolation_1_1_linear" ],
    [ "xpcc::LineSegment2D< T >", "classxpcc_1_1_line_segment2_d.html", "classxpcc_1_1_line_segment2_d" ],
    [ "xpcc::LinkedList< T, Allocator >", "classxpcc_1_1_linked_list.html", "classxpcc_1_1_linked_list" ],
    [ "xpcc::amnb::Listener", "structxpcc_1_1amnb_1_1_listener.html", "structxpcc_1_1amnb_1_1_listener" ],
    [ "xpcc::Lm75< I2cMaster >", "classxpcc_1_1_lm75.html", "classxpcc_1_1_lm75" ],
    [ "xpcc::Location2D< T >", "classxpcc_1_1_location2_d.html", "classxpcc_1_1_location2_d" ],
    [ "xpcc::rtos::Thread::Lock", "classxpcc_1_1rtos_1_1_thread_1_1_lock.html", "classxpcc_1_1rtos_1_1_thread_1_1_lock" ],
    [ "xpcc::atomic::Lock", "classxpcc_1_1atomic_1_1_lock.html", "classxpcc_1_1atomic_1_1_lock" ],
    [ "xpcc::log::Logger", "classxpcc_1_1log_1_1_logger.html", "classxpcc_1_1log_1_1_logger" ],
    [ "xpcc::LUDecomposition", "classxpcc_1_1_l_u_decomposition.html", "classxpcc_1_1_l_u_decomposition" ],
    [ "xpcc::i2c::Master", "classxpcc_1_1i2c_1_1_master.html", "classxpcc_1_1i2c_1_1_master" ],
    [ "xpcc::sab::Master< Interface >", "classxpcc_1_1sab_1_1_master.html", "classxpcc_1_1sab_1_1_master" ],
    [ "xpcc::Matrix< T, ROWS, COLUMNS >", "classxpcc_1_1_matrix.html", "classxpcc_1_1_matrix" ],
    [ "xpcc::MAX6966< Spi, Cs, DRIVERS >", "classxpcc_1_1_m_a_x6966.html", "classxpcc_1_1_m_a_x6966" ],
    [ "xpcc::Mcp23s08< Spi, Cs, Int >", "classxpcc_1_1_mcp23s08.html", "classxpcc_1_1_mcp23s08" ],
    [ "xpcc::Mcp23s17< Spi, Cs, Int >", "classxpcc_1_1_mcp23s17.html", "classxpcc_1_1_mcp23s17" ],
    [ "xpcc::Mcp2515< SPI, CS, INT >", "classxpcc_1_1_mcp2515.html", "classxpcc_1_1_mcp2515" ],
    [ "xpcc::Mcp4922< Spi, Cs, Ldac >", "classxpcc_1_1_mcp4922.html", "classxpcc_1_1_mcp4922" ],
    [ "xpcc::filter::Median< T, N >", "classxpcc_1_1filter_1_1_median.html", "classxpcc_1_1filter_1_1_median" ],
    [ "xpcc::can::Message", "structxpcc_1_1can_1_1_message.html", "structxpcc_1_1can_1_1_message" ],
    [ "xpcc::i2c::MockMaster", "classxpcc_1_1i2c_1_1_mock_master.html", "classxpcc_1_1i2c_1_1_mock_master" ],
    [ "xpcc::MovingAverage< T, N >", "classxpcc_1_1_moving_average.html", "classxpcc_1_1_moving_average" ],
    [ "xpcc::rtos::Mutex", "classxpcc_1_1rtos_1_1_mutex.html", "classxpcc_1_1rtos_1_1_mutex" ],
    [ "xpcc::rtos::MutexGuard", "classxpcc_1_1rtos_1_1_mutex_guard.html", "classxpcc_1_1rtos_1_1_mutex_guard" ],
    [ "my_namespace::MyClass", "classmy__namespace_1_1_my_class.html", "classmy__namespace_1_1_my_class" ],
    [ "xpcc::gpio::Nibble< T3, T2, T1, T0 >", "classxpcc_1_1gpio_1_1_nibble.html", "classxpcc_1_1gpio_1_1_nibble" ],
    [ "xpcc::LinkedList< T, Allocator >::Node", "structxpcc_1_1_linked_list_1_1_node.html", "structxpcc_1_1_linked_list_1_1_node" ],
    [ "xpcc::DoublyLinkedList< T, Allocator >::Node", "structxpcc_1_1_doubly_linked_list_1_1_node.html", "structxpcc_1_1_doubly_linked_list_1_1_node" ],
    [ "xpcc::amnb::Node< Interface >", "classxpcc_1_1amnb_1_1_node.html", "classxpcc_1_1amnb_1_1_node" ],
    [ "xpcc::Nokia6610< SPI, CS, Reset, GE12 >", "classxpcc_1_1_nokia6610.html", "classxpcc_1_1_nokia6610" ],
    [ "xpcc::tmp::NullType", "classxpcc_1_1tmp_1_1_null_type.html", null ],
    [ "xpcc::Pair< T1, T2 >", "classxpcc_1_1_pair.html", "classxpcc_1_1_pair" ],
    [ "xpcc::Pid< T, ScaleFactor >::Parameter", "structxpcc_1_1_pid_1_1_parameter.html", "structxpcc_1_1_pid_1_1_parameter" ],
    [ "xpcc::SCurveController< T >::Parameter", "structxpcc_1_1_s_curve_controller_1_1_parameter.html", "structxpcc_1_1_s_curve_controller_1_1_parameter" ],
    [ "xpcc::PeriodicTimer< T >", "classxpcc_1_1_periodic_timer.html", "classxpcc_1_1_periodic_timer" ],
    [ "xpcc::fat::PhysicalVolume", "classxpcc_1_1fat_1_1_physical_volume.html", "classxpcc_1_1fat_1_1_physical_volume" ],
    [ "xpcc::Pid< T, ScaleFactor >", "classxpcc_1_1_pid.html", "classxpcc_1_1_pid" ],
    [ "xpcc::at91::Pio", "classxpcc_1_1at91_1_1_pio.html", "classxpcc_1_1at91_1_1_pio" ],
    [ "xpcc::at91::Pit", "classxpcc_1_1at91_1_1_pit.html", "classxpcc_1_1at91_1_1_pit" ],
    [ "xpcc::PointSet2D< T >", "classxpcc_1_1_point_set2_d.html", "classxpcc_1_1_point_set2_d" ],
    [ "xpcc::Polygon2D< T >", "classxpcc_1_1_polygon2_d.html", "classxpcc_1_1_polygon2_d" ],
    [ "xpcc::gpio::Port< T7, T6, T5, T4, T3, T2, T1, T0 >", "classxpcc_1_1gpio_1_1_port.html", "classxpcc_1_1gpio_1_1_port" ],
    [ "xpcc::Postman", "classxpcc_1_1_postman.html", "classxpcc_1_1_postman" ],
    [ "xpcc::Pow< B, N >", "classxpcc_1_1_pow.html", null ],
    [ "xpcc::Pow< B, 0 >", "classxpcc_1_1_pow_3_01_b_00_010_01_4.html", null ],
    [ "xpcc::log::Prefix< T, STYLE >", "classxpcc_1_1log_1_1_prefix.html", "classxpcc_1_1log_1_1_prefix" ],
    [ "xpcc::pt::Protothread", "classxpcc_1_1pt_1_1_protothread.html", "classxpcc_1_1pt_1_1_protothread" ],
    [ "xpcc::led::Pulse< LedClass >", "classxpcc_1_1led_1_1_pulse.html", "classxpcc_1_1led_1_1_pulse" ],
    [ "xpcc::at91::Pwm", "classxpcc_1_1at91_1_1_pwm.html", "classxpcc_1_1at91_1_1_pwm" ],
    [ "xpcc::at91::PwmChannel", "classxpcc_1_1at91_1_1_pwm_channel.html", "classxpcc_1_1at91_1_1_pwm_channel" ],
    [ "xpcc::Quaternion< T >", "classxpcc_1_1_quaternion.html", "classxpcc_1_1_quaternion" ],
    [ "xpcc::rtos::Queue< T >", "classxpcc_1_1rtos_1_1_queue.html", "classxpcc_1_1rtos_1_1_queue" ],
    [ "xpcc::atomic::Queue< T, N >", "classxpcc_1_1atomic_1_1_queue.html", "classxpcc_1_1atomic_1_1_queue" ],
    [ "xpcc::Queue< T, Container >", "classxpcc_1_1_queue.html", "classxpcc_1_1_queue" ],
    [ "xpcc::rtos::QueueBase", "classxpcc_1_1rtos_1_1_queue_base.html", "classxpcc_1_1rtos_1_1_queue_base" ],
    [ "xpcc::accessor::Ram< T >", "classxpcc_1_1accessor_1_1_ram.html", "classxpcc_1_1accessor_1_1_ram" ],
    [ "xpcc::filter::Ramp< T >", "classxpcc_1_1filter_1_1_ramp.html", "classxpcc_1_1filter_1_1_ramp" ],
    [ "xpcc::stm32::RandomNumberGenerator", "classxpcc_1_1stm32_1_1_random_number_generator.html", "classxpcc_1_1stm32_1_1_random_number_generator" ],
    [ "xpcc::i2c::ReadAdapter", "classxpcc_1_1i2c_1_1_read_adapter.html", "classxpcc_1_1i2c_1_1_read_adapter" ],
    [ "xpcc::i2c::Delegate::Reading", "structxpcc_1_1i2c_1_1_delegate_1_1_reading.html", "structxpcc_1_1i2c_1_1_delegate_1_1_reading" ],
    [ "xpcc::allocator::Block< T, BLOCKSIZE >::rebind< U >", "structxpcc_1_1allocator_1_1_block_1_1rebind.html", "structxpcc_1_1allocator_1_1_block_1_1rebind" ],
    [ "xpcc::allocator::Dynamic< T >::rebind< U >", "structxpcc_1_1allocator_1_1_dynamic_1_1rebind.html", "structxpcc_1_1allocator_1_1_dynamic_1_1rebind" ],
    [ "xpcc::allocator::Static< T, N >::rebind< U >", "structxpcc_1_1allocator_1_1_static_1_1rebind.html", "structxpcc_1_1allocator_1_1_static_1_1rebind" ],
    [ "xpcc::CanConnector< Driver >::ReceiveListItem", "classxpcc_1_1_can_connector_1_1_receive_list_item.html", "classxpcc_1_1_can_connector_1_1_receive_list_item" ],
    [ "xpcc::tipc::Receiver", "classxpcc_1_1tipc_1_1_receiver.html", "classxpcc_1_1tipc_1_1_receiver" ],
    [ "xpcc::tipc::ReceiverSocket", "classxpcc_1_1tipc_1_1_receiver_socket.html", "classxpcc_1_1tipc_1_1_receiver_socket" ],
    [ "xpcc::ad7280a::RegisterValue", "structxpcc_1_1ad7280a_1_1_register_value.html", "structxpcc_1_1ad7280a_1_1_register_value" ],
    [ "unittest::Reporter", "classunittest_1_1_reporter.html", "classunittest_1_1_reporter" ],
    [ "xpcc::amnb::Response", "classxpcc_1_1amnb_1_1_response.html", "classxpcc_1_1amnb_1_1_response" ],
    [ "xpcc::sab::Response", "classxpcc_1_1sab_1_1_response.html", "classxpcc_1_1sab_1_1_response" ],
    [ "xpcc::ResponseCallback", "classxpcc_1_1_response_callback.html", "classxpcc_1_1_response_callback" ],
    [ "xpcc::ResponseHandle", "classxpcc_1_1_response_handle.html", "classxpcc_1_1_response_handle" ],
    [ "xpcc::color::Rgb", "classxpcc_1_1color_1_1_rgb.html", "classxpcc_1_1color_1_1_rgb" ],
    [ "xpcc::led::Rgb< Red, Green, Blue >", "classxpcc_1_1led_1_1_rgb.html", "classxpcc_1_1led_1_1_rgb" ],
    [ "xpcc::tmp::SameType< T, U >", "structxpcc_1_1tmp_1_1_same_type.html", null ],
    [ "xpcc::tmp::SameType< T, T >", "structxpcc_1_1tmp_1_1_same_type_3_01_t_00_01_t_01_4.html", null ],
    [ "xpcc::Saturated< T >", "classxpcc_1_1_saturated.html", "classxpcc_1_1_saturated" ],
    [ "xpcc::rtos::Scheduler", "classxpcc_1_1rtos_1_1_scheduler.html", "classxpcc_1_1rtos_1_1_scheduler" ],
    [ "xpcc::Scheduler", "classxpcc_1_1_scheduler.html", "classxpcc_1_1_scheduler" ],
    [ "xpcc::Scp1000< Spi, Cs, Int >", "classxpcc_1_1_scp1000.html", "classxpcc_1_1_scp1000" ],
    [ "xpcc::SCurveController< T >", "classxpcc_1_1_s_curve_controller.html", "classxpcc_1_1_s_curve_controller" ],
    [ "xpcc::SCurveGenerator< T >", "classxpcc_1_1_s_curve_generator.html", "classxpcc_1_1_s_curve_generator" ],
    [ "xpcc::tmp::Select< flag, T, U >", "structxpcc_1_1tmp_1_1_select.html", "structxpcc_1_1tmp_1_1_select" ],
    [ "xpcc::tmp::Select< false, T, U >", "structxpcc_1_1tmp_1_1_select_3_01false_00_01_t_00_01_u_01_4.html", "structxpcc_1_1tmp_1_1_select_3_01false_00_01_t_00_01_u_01_4" ],
    [ "xpcc::pt::Semaphore", "classxpcc_1_1pt_1_1_semaphore.html", "classxpcc_1_1pt_1_1_semaphore" ],
    [ "xpcc::rtos::Semaphore", "classxpcc_1_1rtos_1_1_semaphore.html", "classxpcc_1_1rtos_1_1_semaphore" ],
    [ "xpcc::rtos::SemaphoreBase", "classxpcc_1_1rtos_1_1_semaphore_base.html", "classxpcc_1_1rtos_1_1_semaphore_base" ],
    [ "xpcc::CanConnector< Driver >::SendListItem", "classxpcc_1_1_can_connector_1_1_send_list_item.html", "classxpcc_1_1_can_connector_1_1_send_list_item" ],
    [ "xpcc::pc::SerialInterface", "classxpcc_1_1pc_1_1_serial_interface.html", "classxpcc_1_1pc_1_1_serial_interface" ],
    [ "xpcc::pc::SerialPort", "classxpcc_1_1pc_1_1_serial_port.html", "classxpcc_1_1pc_1_1_serial_port" ],
    [ "xpcc::ShiftRegisterInput< Spi, Load, N >", "classxpcc_1_1_shift_register_input.html", "classxpcc_1_1_shift_register_input" ],
    [ "xpcc::ShiftRegisterOutput< Spi, Store, N >", "classxpcc_1_1_shift_register_output.html", "classxpcc_1_1_shift_register_output" ],
    [ "xpcc::SiemensS65< SPI, CS, RS, Reset >", "classxpcc_1_1_siemens_s65.html", "classxpcc_1_1_siemens_s65" ],
    [ "xpcc::sab::Slave< Interface >", "classxpcc_1_1sab_1_1_slave.html", "classxpcc_1_1sab_1_1_slave" ],
    [ "xpcc::Sm130< I2cMaster, Reset >", "classxpcc_1_1_sm130.html", "classxpcc_1_1_sm130" ],
    [ "xpcc::SmartPointer", "classxpcc_1_1_smart_pointer.html", "classxpcc_1_1_smart_pointer" ],
    [ "xpcc::SoftwareI2C< Scl, Sda, Frequency >", "classxpcc_1_1_software_i2_c.html", "classxpcc_1_1_software_i2_c" ],
    [ "xpcc::SoftwareOneWire< Pin >", "classxpcc_1_1_software_one_wire.html", "classxpcc_1_1_software_one_wire" ],
    [ "xpcc::SoftwareSpi< Clk, Mosi, Miso, Frequency >", "classxpcc_1_1_software_spi.html", "classxpcc_1_1_software_spi" ],
    [ "xpcc::at91::Spi0", "classxpcc_1_1at91_1_1_spi0.html", null ],
    [ "xpcc::at91::Spi1", "classxpcc_1_1at91_1_1_spi1.html", null ],
    [ "xpcc::SpiMaster", "classxpcc_1_1_spi_master.html", "classxpcc_1_1_spi_master" ],
    [ "xpcc::atmega::SpiMaster", "classxpcc_1_1atmega_1_1_spi_master.html", "classxpcc_1_1atmega_1_1_spi_master" ],
    [ "xpcc::stm32::SpiMaster1", "classxpcc_1_1stm32_1_1_spi_master1.html", "classxpcc_1_1stm32_1_1_spi_master1" ],
    [ "xpcc::stm32::SpiMaster2", "classxpcc_1_1stm32_1_1_spi_master2.html", "classxpcc_1_1stm32_1_1_spi_master2" ],
    [ "xpcc::stm32::SpiMaster3", "classxpcc_1_1stm32_1_1_spi_master3.html", "classxpcc_1_1stm32_1_1_spi_master3" ],
    [ "xpcc::atxmega::SpiMasterC", "classxpcc_1_1atxmega_1_1_spi_master_c.html", "classxpcc_1_1atxmega_1_1_spi_master_c" ],
    [ "xpcc::atxmega::SpiMasterD", "classxpcc_1_1atxmega_1_1_spi_master_d.html", "classxpcc_1_1atxmega_1_1_spi_master_d" ],
    [ "xpcc::atxmega::SpiMasterE", "classxpcc_1_1atxmega_1_1_spi_master_e.html", "classxpcc_1_1atxmega_1_1_spi_master_e" ],
    [ "xpcc::atxmega::SpiMasterF", "classxpcc_1_1atxmega_1_1_spi_master_f.html", "classxpcc_1_1atxmega_1_1_spi_master_f" ],
    [ "xpcc::SpiRam< Spi, Cs, Hold >", "classxpcc_1_1_spi_ram.html", "classxpcc_1_1_spi_ram" ],
    [ "xpcc::at91::Ssc", "classxpcc_1_1at91_1_1_ssc.html", null ],
    [ "xpcc::St7036< SPI, CS, RS, Width, Heigth >", "classxpcc_1_1_st7036.html", "classxpcc_1_1_st7036" ],
    [ "xpcc::St7565< SPI, CS, A0, Reset, Width, Height, TopView >", "classxpcc_1_1_st7565.html", "classxpcc_1_1_st7565" ],
    [ "xpcc::Stack< T, Container >", "classxpcc_1_1_stack.html", "classxpcc_1_1_stack" ],
    [ "xpcc::stm32::CanFilter::StandardFilterMask", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_filter_mask.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_filter_mask" ],
    [ "xpcc::stm32::CanFilter::StandardFilterMaskShort", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_filter_mask_short.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_filter_mask_short" ],
    [ "xpcc::stm32::CanFilter::StandardIdentifier", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_identifier.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_identifier" ],
    [ "xpcc::stm32::CanFilter::StandardIdentifierShort", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_identifier_short.html", "structxpcc_1_1stm32_1_1_can_filter_1_1_standard_identifier_short" ],
    [ "xpcc::i2c::Delegate::Starting", "structxpcc_1_1i2c_1_1_delegate_1_1_starting.html", "structxpcc_1_1i2c_1_1_delegate_1_1_starting" ],
    [ "xpcc::allocator::Static< T, N >", "classxpcc_1_1allocator_1_1_static.html", "classxpcc_1_1allocator_1_1_static" ],
    [ "xpcc::tmp::static_assert_test< x >", "structxpcc_1_1tmp_1_1static__assert__test.html", null ],
    [ "xpcc::tmp::STATIC_ASSERTION_FAILURE< true >", "structxpcc_1_1tmp_1_1_s_t_a_t_i_c___a_s_s_e_r_t_i_o_n___f_a_i_l_u_r_e_3_01true_01_4.html", null ],
    [ "xpcc::log::StdColour< TEXT, BACKGROUND, STYLE >", "classxpcc_1_1log_1_1_std_colour.html", "classxpcc_1_1log_1_1_std_colour" ],
    [ "xpcc::log::Style< STYLE >", "classxpcc_1_1log_1_1_style.html", "classxpcc_1_1log_1_1_style" ],
    [ "xpcc::log::StyleWrapper< STYLE >", "classxpcc_1_1log_1_1_style_wrapper.html", "classxpcc_1_1log_1_1_style_wrapper" ],
    [ "xpcc::tmp::SuperSubclass< T, U >", "structxpcc_1_1tmp_1_1_super_subclass.html", null ],
    [ "xpcc::tmp::SuperSubclass< T, void >", "structxpcc_1_1tmp_1_1_super_subclass_3_01_t_00_01void_01_4.html", null ],
    [ "xpcc::tmp::SuperSubclass< void, U >", "structxpcc_1_1tmp_1_1_super_subclass_3_01void_00_01_u_01_4.html", null ],
    [ "xpcc::tmp::SuperSubclass< void, void >", "structxpcc_1_1tmp_1_1_super_subclass_3_01void_00_01void_01_4.html", null ],
    [ "xpcc::tmp::SuperSubclassStrict< T, U >", "structxpcc_1_1tmp_1_1_super_subclass_strict.html", null ],
    [ "xpcc::stm32::SysTickTimer", "classxpcc_1_1stm32_1_1_sys_tick_timer.html", "classxpcc_1_1stm32_1_1_sys_tick_timer" ],
    [ "xpcc::Task", "classxpcc_1_1_task.html", "classxpcc_1_1_task" ],
    [ "xpcc::Scheduler::Task", "classxpcc_1_1_scheduler_1_1_task.html", "classxpcc_1_1_scheduler_1_1_task" ],
    [ "xpcc::pc::Terminal", "classxpcc_1_1pc_1_1_terminal.html", "classxpcc_1_1pc_1_1_terminal" ],
    [ "unittest::TestSuite", "classunittest_1_1_test_suite.html", "classunittest_1_1_test_suite" ],
    [ "xpcc::rtos::Thread", "classxpcc_1_1rtos_1_1_thread.html", "classxpcc_1_1rtos_1_1_thread" ],
    [ "xpcc::Timeout< T >", "classxpcc_1_1_timeout.html", "classxpcc_1_1_timeout" ],
    [ "xpcc::at91::Timer", "classxpcc_1_1at91_1_1_timer.html", "classxpcc_1_1at91_1_1_timer" ],
    [ "xpcc::at91::Timer0", "classxpcc_1_1at91_1_1_timer0.html", "classxpcc_1_1at91_1_1_timer0" ],
    [ "xpcc::at91::Timer1", "classxpcc_1_1at91_1_1_timer1.html", "classxpcc_1_1at91_1_1_timer1" ],
    [ "xpcc::stm32::Timer1", "classxpcc_1_1stm32_1_1_timer1.html", "classxpcc_1_1stm32_1_1_timer1" ],
    [ "xpcc::stm32::Timer2", "classxpcc_1_1stm32_1_1_timer2.html", "classxpcc_1_1stm32_1_1_timer2" ],
    [ "xpcc::at91::Timer2", "classxpcc_1_1at91_1_1_timer2.html", "classxpcc_1_1at91_1_1_timer2" ],
    [ "xpcc::stm32::Timer3", "classxpcc_1_1stm32_1_1_timer3.html", "classxpcc_1_1stm32_1_1_timer3" ],
    [ "xpcc::stm32::Timer4", "classxpcc_1_1stm32_1_1_timer4.html", "classxpcc_1_1stm32_1_1_timer4" ],
    [ "xpcc::stm32::Timer5", "classxpcc_1_1stm32_1_1_timer5.html", "classxpcc_1_1stm32_1_1_timer5" ],
    [ "xpcc::stm32::Timer6", "classxpcc_1_1stm32_1_1_timer6.html", "classxpcc_1_1stm32_1_1_timer6" ],
    [ "xpcc::stm32::Timer7", "classxpcc_1_1stm32_1_1_timer7.html", "classxpcc_1_1stm32_1_1_timer7" ],
    [ "xpcc::stm32::Timer8", "classxpcc_1_1stm32_1_1_timer8.html", "classxpcc_1_1stm32_1_1_timer8" ],
    [ "xpcc::atxmega::TimerC0", "classxpcc_1_1atxmega_1_1_timer_c0.html", "classxpcc_1_1atxmega_1_1_timer_c0" ],
    [ "xpcc::atxmega::TimerC1", "classxpcc_1_1atxmega_1_1_timer_c1.html", "classxpcc_1_1atxmega_1_1_timer_c1" ],
    [ "xpcc::atxmega::TimerD0", "classxpcc_1_1atxmega_1_1_timer_d0.html", "classxpcc_1_1atxmega_1_1_timer_d0" ],
    [ "xpcc::atxmega::TimerD1", "classxpcc_1_1atxmega_1_1_timer_d1.html", "classxpcc_1_1atxmega_1_1_timer_d1" ],
    [ "xpcc::atxmega::TimerE0", "classxpcc_1_1atxmega_1_1_timer_e0.html", "classxpcc_1_1atxmega_1_1_timer_e0" ],
    [ "xpcc::atxmega::TimerE1", "classxpcc_1_1atxmega_1_1_timer_e1.html", "classxpcc_1_1atxmega_1_1_timer_e1" ],
    [ "xpcc::atxmega::TimerF0", "classxpcc_1_1atxmega_1_1_timer_f0.html", "classxpcc_1_1atxmega_1_1_timer_f0" ],
    [ "xpcc::atxmega::TimerF1", "classxpcc_1_1atxmega_1_1_timer_f1.html", "classxpcc_1_1atxmega_1_1_timer_f1" ],
    [ "xpcc::atxmega::TimerInterruptC0", "classxpcc_1_1atxmega_1_1_timer_interrupt_c0.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_c0" ],
    [ "xpcc::atxmega::TimerInterruptC1", "classxpcc_1_1atxmega_1_1_timer_interrupt_c1.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_c1" ],
    [ "xpcc::atxmega::TimerInterruptD0", "classxpcc_1_1atxmega_1_1_timer_interrupt_d0.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_d0" ],
    [ "xpcc::atxmega::TimerInterruptD1", "classxpcc_1_1atxmega_1_1_timer_interrupt_d1.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_d1" ],
    [ "xpcc::atxmega::TimerInterruptE0", "classxpcc_1_1atxmega_1_1_timer_interrupt_e0.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_e0" ],
    [ "xpcc::atxmega::TimerInterruptE1", "classxpcc_1_1atxmega_1_1_timer_interrupt_e1.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_e1" ],
    [ "xpcc::atxmega::TimerInterruptF0", "classxpcc_1_1atxmega_1_1_timer_interrupt_f0.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_f0" ],
    [ "xpcc::atxmega::TimerInterruptF1", "classxpcc_1_1atxmega_1_1_timer_interrupt_f1.html", "classxpcc_1_1atxmega_1_1_timer_interrupt_f1" ],
    [ "xpcc::Timestamp", "classxpcc_1_1_timestamp.html", "classxpcc_1_1_timestamp" ],
    [ "xpcc::TipcConnector", "classxpcc_1_1_tipc_connector.html", "classxpcc_1_1_tipc_connector" ],
    [ "xpcc::TLC594X< CHANNELS, Spi, Xlat, Vprog, Xerr >", "classxpcc_1_1_t_l_c594_x.html", "classxpcc_1_1_t_l_c594_x" ],
    [ "xpcc::led::TLC594XLed< PwmController, CHANNEL, PwmTable, PwmTableSize >", "classxpcc_1_1led_1_1_t_l_c594_x_led.html", "classxpcc_1_1led_1_1_t_l_c594_x_led" ],
    [ "xpcc::Tmp102< I2cMaster >", "classxpcc_1_1_tmp102.html", "classxpcc_1_1_tmp102" ],
    [ "xpcc::tipc::Transmitter", "classxpcc_1_1tipc_1_1_transmitter.html", "classxpcc_1_1tipc_1_1_transmitter" ],
    [ "xpcc::sab::Transmitter", "classxpcc_1_1sab_1_1_transmitter.html", "classxpcc_1_1sab_1_1_transmitter" ],
    [ "xpcc::amnb::Transmitter", "classxpcc_1_1amnb_1_1_transmitter.html", "classxpcc_1_1amnb_1_1_transmitter" ],
    [ "xpcc::tipc::TransmitterSocket", "classxpcc_1_1tipc_1_1_transmitter_socket.html", "classxpcc_1_1tipc_1_1_transmitter_socket" ],
    [ "xpcc::at91::Twi", "classxpcc_1_1at91_1_1_twi.html", null ],
    [ "xpcc::at91::Uart0", "classxpcc_1_1at91_1_1_uart0.html", "classxpcc_1_1at91_1_1_uart0" ],
    [ "xpcc::lpc2000::Uart0", "classxpcc_1_1lpc2000_1_1_uart0.html", "classxpcc_1_1lpc2000_1_1_uart0" ],
    [ "xpcc::lpc2000::Uart1", "classxpcc_1_1lpc2000_1_1_uart1.html", "classxpcc_1_1lpc2000_1_1_uart1" ],
    [ "xpcc::at91::Uart1", "classxpcc_1_1at91_1_1_uart1.html", "classxpcc_1_1at91_1_1_uart1" ],
    [ "xpcc::lpc2000::Uart2", "classxpcc_1_1lpc2000_1_1_uart2.html", "classxpcc_1_1lpc2000_1_1_uart2" ],
    [ "xpcc::lpc2000::Uart3", "classxpcc_1_1lpc2000_1_1_uart3.html", "classxpcc_1_1lpc2000_1_1_uart3" ],
    [ "xpcc::stm32::Uart4", "classxpcc_1_1stm32_1_1_uart4.html", "classxpcc_1_1stm32_1_1_uart4" ],
    [ "xpcc::stm32::Uart5", "classxpcc_1_1stm32_1_1_uart5.html", "classxpcc_1_1stm32_1_1_uart5" ],
    [ "xpcc::stm32::UartBase", "classxpcc_1_1stm32_1_1_uart_base.html", "classxpcc_1_1stm32_1_1_uart_base" ],
    [ "xpcc::atxmega::UartBase", "classxpcc_1_1atxmega_1_1_uart_base.html", "classxpcc_1_1atxmega_1_1_uart_base" ],
    [ "UartInterface", "class_uart_interface.html", "class_uart_interface" ],
    [ "xpcc::atxmega::UartSpiMasterC0", "classxpcc_1_1atxmega_1_1_uart_spi_master_c0.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_c0" ],
    [ "xpcc::atxmega::UartSpiMasterC1", "classxpcc_1_1atxmega_1_1_uart_spi_master_c1.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_c1" ],
    [ "xpcc::atxmega::UartSpiMasterD0", "classxpcc_1_1atxmega_1_1_uart_spi_master_d0.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_d0" ],
    [ "xpcc::atxmega::UartSpiMasterD1", "classxpcc_1_1atxmega_1_1_uart_spi_master_d1.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_d1" ],
    [ "xpcc::atxmega::UartSpiMasterE0", "classxpcc_1_1atxmega_1_1_uart_spi_master_e0.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_e0" ],
    [ "xpcc::atxmega::UartSpiMasterE1", "classxpcc_1_1atxmega_1_1_uart_spi_master_e1.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_e1" ],
    [ "xpcc::atxmega::UartSpiMasterF0", "classxpcc_1_1atxmega_1_1_uart_spi_master_f0.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_f0" ],
    [ "xpcc::atxmega::UartSpiMasterF1", "classxpcc_1_1atxmega_1_1_uart_spi_master_f1.html", "classxpcc_1_1atxmega_1_1_uart_spi_master_f1" ],
    [ "xpcc::UnixTime", "classxpcc_1_1_unix_time.html", "classxpcc_1_1_unix_time" ],
    [ "xpcc::atomic::Unlock", "classxpcc_1_1atomic_1_1_unlock.html", "classxpcc_1_1atomic_1_1_unlock" ],
    [ "xpcc::gpio::Unused", "classxpcc_1_1gpio_1_1_unused.html", "classxpcc_1_1gpio_1_1_unused" ],
    [ "xpcc::stm32::Usart1", "classxpcc_1_1stm32_1_1_usart1.html", "classxpcc_1_1stm32_1_1_usart1" ],
    [ "xpcc::stm32::Usart2", "classxpcc_1_1stm32_1_1_usart2.html", "classxpcc_1_1stm32_1_1_usart2" ],
    [ "xpcc::stm32::Usart3", "classxpcc_1_1stm32_1_1_usart3.html", "classxpcc_1_1stm32_1_1_usart3" ],
    [ "xpcc::stm32::Usart6", "classxpcc_1_1stm32_1_1_usart6.html", "classxpcc_1_1stm32_1_1_usart6" ],
    [ "xpcc::at91::Usb", "classxpcc_1_1at91_1_1_usb.html", null ],
    [ "xpcc::Vector< T, N >", "classxpcc_1_1_vector.html", "classxpcc_1_1_vector" ],
    [ "xpcc::Vector< T, 1 >", "classxpcc_1_1_vector_3_01_t_00_011_01_4.html", "classxpcc_1_1_vector_3_01_t_00_011_01_4" ],
    [ "xpcc::Vector< T, 2 >", "classxpcc_1_1_vector_3_01_t_00_012_01_4.html", "classxpcc_1_1_vector_3_01_t_00_012_01_4" ],
    [ "xpcc::Vector< T, 3 >", "classxpcc_1_1_vector_3_01_t_00_013_01_4.html", "classxpcc_1_1_vector_3_01_t_00_013_01_4" ],
    [ "xpcc::Vector< T, 4 >", "classxpcc_1_1_vector_3_01_t_00_014_01_4.html", "classxpcc_1_1_vector_3_01_t_00_014_01_4" ],
    [ "xpcc::lpc::Vic", "classxpcc_1_1lpc_1_1_vic.html", null ],
    [ "xpcc::at91::Watchdog", "classxpcc_1_1at91_1_1_watchdog.html", null ],
    [ "xpcc::atxmega::WaveformC", "classxpcc_1_1atxmega_1_1_waveform_c.html", "classxpcc_1_1atxmega_1_1_waveform_c" ],
    [ "xpcc::atxmega::WaveformD", "classxpcc_1_1atxmega_1_1_waveform_d.html", "classxpcc_1_1atxmega_1_1_waveform_d" ],
    [ "xpcc::atxmega::WaveformE", "classxpcc_1_1atxmega_1_1_waveform_e.html", "classxpcc_1_1atxmega_1_1_waveform_e" ],
    [ "xpcc::atxmega::WaveformF", "classxpcc_1_1atxmega_1_1_waveform_f.html", "classxpcc_1_1atxmega_1_1_waveform_f" ],
    [ "xpcc::i2c::WriteAdapter", "classxpcc_1_1i2c_1_1_write_adapter.html", "classxpcc_1_1i2c_1_1_write_adapter" ],
    [ "xpcc::CharacterDisplay::Writer", "classxpcc_1_1_character_display_1_1_writer.html", "classxpcc_1_1_character_display_1_1_writer" ],
    [ "xpcc::GraphicDisplay::Writer", "classxpcc_1_1_graphic_display_1_1_writer.html", "classxpcc_1_1_graphic_display_1_1_writer" ],
    [ "xpcc::i2c::WriteReadAdapter", "classxpcc_1_1i2c_1_1_write_read_adapter.html", "classxpcc_1_1i2c_1_1_write_read_adapter" ],
    [ "xpcc::i2c::Delegate::Writing", "structxpcc_1_1i2c_1_1_delegate_1_1_writing.html", "structxpcc_1_1i2c_1_1_delegate_1_1_writing" ]
];