xpcc: xpcc::atxmega::UartBase Class Reference
xpcc::atxmega::UartBase Class Reference
UART module
Base class for the UART classes.
#include <xpcc/architecture/platform/avr/atxmega/uart.hpp>
Static Public Member Functions
static void write (char data)
Write a single byte.
static void write (const char *string)
Write a null-terminated string.
static void write (const char *buffer, uint8_t nbyte)
Write a block of bytes.
static bool read (char &data)
Read a single byte.
static uint8_t read (char *buffer, uint8_t nbyte)
Read a block of bytes.
Static Protected Member Functions
static void initialize ()
Initialize UART module.
static void setBaudrate (uint32_t baudrate)
Set baud rate.
static uint16_t baudBselFromBaudscale (uint32_t const baudrate, int8_t const bscale)
Find the BSEL value depending on the BSCALE value and baudrate.
static int8_t bScale (uint32_t const baudrate)
Find a suitable BSCALE value for a given baudrate by trial-and-error.
static uint8_t bScaleUnsigned (uint32_t baudrate)
Convert the signed BSCALE value unsigned.
static uint16_t bSel (uint32_t const baudrate)
Select BSEL value.
Detailed Description
Provides the common interface for all UARTs and alike. This should be generalised for all platforms (at least atmega, atxmega and stm32)
Definition at line 51 of file avr/atxmega/uart.hpp.
Member Function Documentation
static void xpcc::atxmega::UartBase::write (char data) [static]
Parameters:
data Single byte to write
static void xpcc::atxmega::UartBase::write (const char * string) [static]
Parameters:
*string String to write
The string must end with '\0'.
static void xpcc::atxmega::UartBase::write (const char * buffer, uint8_t nbyte) [static]
Parameters:
*buffer Pointer to buffer with data to write
nbyte Number of bytes to write
static bool xpcc::atxmega::UartBase::read (char & data) [static]
Parameters:
&data Byte read, if any
Returns:
true if a byte was received,
false otherwise
static uint8_t xpcc::atxmega::UartBase::read (char * buffer, uint8_t nbyte) [static]
This is non-blocking. If no data is available this function waits about 1.5 times of a frame length. This is only correct at a baud rate of 115200.
Parameters:
*buffer Pointer to a buffer big enough to store n bytes
nbyte Number of bytes to be read
Returns:
Number of bytes which could be read, maximum n
static void xpcc::atxmega::UartBase::initialize () [static, protected]
Set the output and input pins, the interrupts and enables transceiver and receiver. Does *not* set the baudrate. This should be done *before*.
static void xpcc::atxmega::UartBase::setBaudrate (uint32_t baudrate) [inline, static, protected]
See Constructor.
Parameters:
baudrate desired baud rate, must be constant at compile time
static uint16_t xpcc::atxmega::UartBase::baudBselFromBaudscale (uint32_t const baudrate, int8_t const bscale) [inline, static, protected]
Parameters:
baudrate Desired baudrate
bscale The fractional divider.
The formula is from table 21-1 on page 238 of the datasheet.
Definition at line 138 of file avr/atxmega/uart.hpp.
Referenced by bScale(), and bSel().
static int8_t xpcc::atxmega::UartBase::bScale (uint32_t const baudrate) [inline, static, protected]
Parameters:
baudrate Desired baudrate.
Definition at line 153 of file avr/atxmega/uart.hpp.
References baudBselFromBaudscale().
Referenced by bScaleUnsigned(), and bSel().
static uint8_t xpcc::atxmega::UartBase::bScaleUnsigned (uint32_t baudrate) [inline, static, protected]
Parameters:
baudrate Desired baud rate.
Returns:
bscale_unsigned Unsigned BSCALE value.
Definition at line 207 of file avr/atxmega/uart.hpp.
References bScale().
static uint16_t xpcc::atxmega::UartBase::bSel (uint32_t const baudrate) [inline, static, protected]
Parameters:
baudrate Desired baud rate.
Definition at line 229 of file avr/atxmega/uart.hpp.
References baudBselFromBaudscale(), and bScale().
The documentation for this class was generated from the following file:
avr/atxmega/uart.hpp