XPCC: xpcc::atmega::Adc Class Reference
xpcc::atmega::Adc Class Reference
megaAVR
Generic Analog/Digital-Converter module.
#include <xpcc/architecture/platform/avr/atmega/adc.hpp>
Public Types
enum Reference { REFERENCE_AREF = 0, REFERENCE_INTERNAL_AVCC = 0x40, REFERENCE_INTERNAL_1V1 = 0xc0 }
enum Prescaler {
PRESCALER_2 = 0x01, PRESCALER_4 = 0x02, PRESCALER_8 = 0x03, PRESCALER_16 = 0x04,
PRESCALER_32 = 0x05, PRESCALER_64 = 0x06, PRESCALER_128 = 0x07
}
Static Public Member Functions
static bool setChannel (uint8_t channel)
Analog channel selection.
static uint8_t getChannel ()
static void setEnableAdc (bool enable)
Enables the ADC.
static void setStartConversion ()
In Single Conversion mode, this starts each conversion.
static void setAutoTriggerEnable (bool enable)
Enable auto triggering of the ADC.
static void setFreeRunningMode (bool enable)
Enables free running mode.
static bool isInterruptFlagSet ()
static void clearInterruptFlag ()
Clears the interrupt flag.
static void setInterruptEnable (bool enable)
Enables the ADC Conversion Complete Interrupt.
static void setPrescaler (Prescaler prescaler)
Set the division factor between the system clock frequency and the input clock to the ADC.
static void setAutoTriggerSource (uint8_t source)
Selects which source will trigger an ADC conversion.
static void setHighSpeedMode (bool enable)
Enable the ADC High Speed mode.
static void setCurrentSourceEnable (bool enable)
Source a 100μA current to the AREF pin.
static bool isAvddOk ()
The analog functions of the ADC are powered from the AVDD domain.
static bool isReferenceVoltageOk ()
The status of the internal generated reference voltage can be monitored through this bit.
static void setAnalogChannelChange ()
The user can force a reset of the analog blocks by setting this without requesting a different channel.
static uint16_t getDataRegister ()
static void initialize (Reference referenceVoltage, Prescaler prescaler)
Initialize and enable the A/D converter.
static void enableFreeRunningMode ()
Correctly enables Free Running Mode.
static uint16_t readChannel (uint8_t channel)
Read the value an analog channel.
static bool startConversion (uint8_t channel)
Start a new conversion.
static bool isFinished ()
Check if the conversion is finished.
static uint16_t getValue ()
the most recent 16bit result of the ADC conversion
Detailed Description
This class aims at providing a common interface to all the different register layouts of the ADC modules in most ATmegas. It takes into consideration restrictions and extensions in ADC functionality and provides the appropriate methods to configure them.
This class enables you to address and use a broader array of ATmegas with similar ADC functionality without changing a single line of code.
For best use of this class, check your device's datasheet for the supported functionality.
ADC clock frequency should be between 50 and 200 kHz for maximum resolution. If less than 10-bits are needed the frequency can be higher.
Synchronous mode (waits until the ADC is finished):
 #include <xpcc/architecture/atmega/adc.hpp>
 int
 main()
 {
     xpcc::Adc::initialize(
             xpcc::Adc::REFERENCE_INTERNAL_2V56,
             xpcc::Adc::PRESCALER_64);
     ...
     // read channel 2
     uint16_t value = xpcc::Adc::readChannel(2);
     ...
 }
Asynchronous mode:
 // start a new conversion on channel 3
 xpcc::Adc::startConversion(3);
 // do something usefull while waiting for the result
 while (!xpcc::Adc::isFinished())
     ;
 // read the converted value
 uint16_t value = xpcc::Adc::getValue();
Alternatively you can use the AdcInterrupt class to attach a function to the ADC Interrupt handler for true asynchonous mode.
For a detailed example see the adc folder in the examples folder.
See also:
AdcInterrupt
Author:
Fabian Greif, Niklas Hauser
Member Function Documentation
static bool xpcc::atmega::Adc::setChannel (uint8_t channel) [inline, static]
Selects which analog inputs are connected to the ADC. If this is changed during a conversion, the change will not go in effect until this conversion is complete.
Available on all ATmegas.
Definition at line 198 of file avr/atmega/adc.hpp.
Referenced by startConversion().
static uint8_t xpcc::atmega::Adc::getChannel () [inline, static]
Returns:
The analog channel connected to the ADC
Available on all ATmegas.
Definition at line 222 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setEnableAdc (bool enable) [inline, static]
Available on all ATmegas.
Definition at line 265 of file avr/atmega/adc.hpp.
Referenced by initialize().
static void xpcc::atmega::Adc::setStartConversion () [inline, static]
In Free Running mode, this starts the first conversion.
Available on all ATmegas.
Definition at line 276 of file avr/atmega/adc.hpp.
Referenced by startConversion().
static void xpcc::atmega::Adc::setAutoTriggerEnable (bool enable) [inline, static]
The ADC will start a conversion on a positive edge of the selected trigger signal.
See also:
setAutoTriggerSource
Definition at line 289 of file avr/atmega/adc.hpp.
Referenced by enableFreeRunningMode().
static void xpcc::atmega::Adc::setFreeRunningMode (bool enable) [inline, static]
The ADC will continously start conversions and provide the most recent result in the ADC register.
Definition at line 302 of file avr/atmega/adc.hpp.
Referenced by enableFreeRunningMode().
static bool xpcc::atmega::Adc::isInterruptFlagSet () [inline, static]
Returns:
true if the flag is set
Available on all ATmegas.
Definition at line 313 of file avr/atmega/adc.hpp.
Referenced by readChannel(), and isFinished().
static void xpcc::atmega::Adc::clearInterruptFlag () [inline, static]
Available on all ATmegas.
Definition at line 323 of file avr/atmega/adc.hpp.
Referenced by startConversion().
static void xpcc::atmega::Adc::setInterruptEnable (bool enable) [inline, static]
Available on all ATmegas.
See also:
AdcInterrupt
Definition at line 335 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setAutoTriggerSource (uint8_t source) [inline, static]
A conversion will be triggered by the rising edge of the selected Interrupt Flag. Note that switching from a trigger source that is cleared to a trigger source that is set, will generate a positive edge on the trigger signal. Set to 0 to enable Free Running Mode.
Definition at line 363 of file avr/atmega/adc.hpp.
Referenced by enableFreeRunningMode().
static void xpcc::atmega::Adc::setHighSpeedMode (bool enable) [inline, static]
Set this if you wish to convert with an ADC clock frequency higher than 200KHz. Clear this bit to reduce the power consumption of the ADC when the ADC clock frequency is lower than 200KHz.
Only Available on the M- and C-series ATmega's!
Definition at line 392 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setCurrentSourceEnable (bool enable) [inline, static]
Clear this bit to use AREF pin as Analog Reference pin.
Only Available on the M- and C-series ATmega's!
Definition at line 404 of file avr/atmega/adc.hpp.
static bool xpcc::atmega::Adc::isAvddOk () [inline, static]
AVDD is supplied from an internal voltage regulator. Enabling the ADC will power-up the AVDD domain if not already requested by another functional group of the device. This method allows the user to monitor (poll) the status of the AVDD domain.
Returns:
true indicates that AVDD has been powered-up.
Only Available on the ATmega128RFA1!
Definition at line 424 of file avr/atmega/adc.hpp.
static bool xpcc::atmega::Adc::isReferenceVoltageOk () [inline, static]
After enabling the ADC and setting the reference voltage, it will be available after a start-up delay.
Returns:
true which indicates that the internal generated reference voltage is approaching final levels.
Only Available on the ATmega128RFA1!
Definition at line 440 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setAnalogChannelChange () [inline, static]
The analog blocks of the ADC will be reset to handle possible new voltage ranges. Such a reset phase is especially important for the gain amplifier. It could be temporarily disabled by a large step of its input common voltage leading to erroneous A/D conversion results.
Only Available on the ATmega128RFA1!
Definition at line 455 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::initialize (Reference referenceVoltage, Prescaler prescaler) [inline, static]
Available on all ATmegas.
Definition at line 486 of file avr/atmega/adc.hpp.
References setPrescaler(), and setEnableAdc().
static void xpcc::atmega::Adc::enableFreeRunningMode () [inline, static]
Available on all ATmegas.
Definition at line 501 of file avr/atmega/adc.hpp.
References setFreeRunningMode(), setAutoTriggerEnable(), and setAutoTriggerSource().
static uint16_t xpcc::atmega::Adc::readChannel (uint8_t channel) [inline, static]
A normal conversion takes 13 ADC clock cycles. With a clock frequency of for example 200 kHz a conversion therefore needs 65 microseconds. This time increases with a lower frequency.
Available on all ATmegas.
Definition at line 521 of file avr/atmega/adc.hpp.
References startConversion(), and isInterruptFlagSet().
static bool xpcc::atmega::Adc::startConversion (uint8_t channel) [inline, static]
Available on all ATmegas.
Definition at line 538 of file avr/atmega/adc.hpp.
References setChannel(), clearInterruptFlag(), and setStartConversion().
Referenced by readChannel().
static bool xpcc::atmega::Adc::isFinished () [inline, static]
Available on all ATmegas.
Definition at line 554 of file avr/atmega/adc.hpp.
References isInterruptFlagSet().
static uint16_t xpcc::atmega::Adc::getValue () [inline, static]
Available on all ATmegas.
Definition at line 565 of file avr/atmega/adc.hpp.
The documentation for this class was generated from the following file:
avr/atmega/adc.hpp