XPCC: xpcc::atxmega::AsynchronousI2cMasterE Class Reference
xpcc::atxmega::AsynchronousI2cMasterE Class Reference
I2C Module | (I2C) Inter-Integrated Circuit
Asynchronous I2C master module for Port E.
#include <xpcc/architecture/platform/avr/atxmega/i2c/i2c_master_e.hpp>
Static Public Member Functions
static void initialize (uint8_t baud, bool pullUpResistors=false)
static void reset ()
Performed a software reset of bus driver.
static bool start (uint8_t slaveAddress)
Requests bus control and generates a start condition.
static void restart (uint8_t slaveAddress)
Restarts the bus without loosing control.
static void read (uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Read a block of data.
static void write (uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write a block of data.
static void writeRead (uint8_t *data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write and read blocks of data.
static void attachDelegate (xpcc::i2c::Delegate *object)
Attach a delegate, which is called in the interrupt at the (un-)successful completion of an action (read or write) or after a restart.
static xpcc::i2c::ErrorState getErrorState ()
Check current ErrorState.
static xpcc::i2c::BusyState getBusyState ()
Check current BusyState.
static xpcc::i2c::BusState getBusState ()
Check the BusState after last operation.
static bool startWrite (uint8_t slaveAddress, uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::WRITE_STOP)
writes a block of data, if bus state allows.
static bool startRead (uint8_t slaveAddress, uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Read a block of data, if bus state allows.
static bool startWriteRead (uint8_t slaveAddress, uint8_t *data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write and read blocks of data, if bus state allows.
static void stop ()
Detailed Description
Interrupts must be enabled.
Author:
Niklas Hauser
Definition at line 57 of file i2c_master_e.hpp.
Member Function Documentation
static bool xpcc::atxmega::AsynchronousI2cMasterE::start (uint8_t slaveAddress) [static]
Parameters:
[in] slaveAddress Shifted 7-bit address of the slave device. LSB must be zero.
Returns:
Caller gains control if true. Call has no effect if false.
Reimplemented from xpcc::i2c::Master.
Referenced by startRead(), startWrite(), and startWriteRead().
static void xpcc::atxmega::AsynchronousI2cMasterE::restart (uint8_t slaveAddress) [static]
Multiple calls will result in generating only one start condition.
Parameters:
[in] slaveAddress Shifted 7-bit address of the slave device. LSB must be zero.
Reimplemented from xpcc::i2c::Master.
static void xpcc::atxmega::AsynchronousI2cMasterE::read (uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method only if BusState allows reading.
Parameters:
[out] *data Pointer to buffer where received data should be stored. This must remain valid during operation is in progress.
[in] size Number of bytes to be received
[in] param See description OperationParameter. Default is READ_STOP.
Reimplemented from xpcc::i2c::Master.
static void xpcc::atxmega::AsynchronousI2cMasterE::write (uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method if BusState allows writing.
Parameters:
data Pointer to buffer containing data to send. This must remain valid during operation is in progress.
size Number of bytes to be send
[in] param See description OperationParameter. Default is WRITE_STOP.
Reimplemented from xpcc::i2c::Master.
static void xpcc::atxmega::AsynchronousI2cMasterE::writeRead (uint8_t * data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method if BusState allows writing.
Parameters:
data Pointer to the buffer containing data to be send and where received data should be stored. This must remain valid while the operation is in progress. The data sent will be (partially) overwritten by the data received! The Delegate will not be called after the write operation completed, but only after the receive operation completed.
writeSize Number of bytes to be send
readSize Number of bytes to be received
[in] param See description OperationParameter. Default is READ_STOP.
Reimplemented from xpcc::i2c::Master.
Referenced by startRead(), startWrite(), and startWriteRead().
static void xpcc::atxmega::AsynchronousI2cMasterE::attachDelegate (xpcc::i2c::Delegate * object) [static]
This allows for true asynchonous operation, multistage driver design and performance gain by premature data evaluation. The delegate gets reset after it has been called, meaning it has to be (re-)attached everytime a new action is being committed.
Parameters:
object class that inherits from Delegate
Reimplemented from xpcc::i2c::Master.
static xpcc::i2c::BusState xpcc::atxmega::AsynchronousI2cMasterE::getBusState () [static]
This message should only be called by owner while BusyState is occupied. In other cases returned value is not relevant.
Returns:
BusState if BusyState is occupied
Reimplemented from xpcc::i2c::Master.
static bool xpcc::atxmega::AsynchronousI2cMasterE::startWrite (uint8_t slaveAddress, uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::WRITE_STOP) [inline, static]
 if (start(slaveAddress)) {
       write(data, size, param);
       return true;
 }
 return false;
See also:
start()
write()
Reimplemented from xpcc::i2c::Master.
Definition at line 97 of file i2c_master_e.hpp.
References start(), xpcc::i2c::WRITE_RESTART, and writeRead().
static bool xpcc::atxmega::AsynchronousI2cMasterE::startRead (uint8_t slaveAddress, uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [inline, static]
 if (start(slaveAddress, xpcc::i2c::READ)) {
       read(data, size, param);
       return true;
 }
 return false;
See also:
start()
read()
Reimplemented from xpcc::i2c::Master.
Definition at line 108 of file i2c_master_e.hpp.
References xpcc::i2c::READ_RESTART, start(), and writeRead().
static bool xpcc::atxmega::AsynchronousI2cMasterE::startWriteRead (uint8_t slaveAddress, uint8_t * data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [inline, static]
 if (start(slaveAddress)) {
       writeRead(data, writeSize, readSize, param);
       return true;
 }
 return false;
See also:
start()
writeRead()
Reimplemented from xpcc::i2c::Master.
Definition at line 119 of file i2c_master_e.hpp.
References xpcc::i2c::READ_RESTART, start(), and writeRead().
The documentation for this class was generated from the following file:
i2c_master_e.hpp