XPCC: xpcc::stm32::I2c2 Class Reference
xpcc::stm32::I2c2 Class Reference
STM32Fxxx
I2C2 Module.
#include <xpcc/architecture/platform/cortex_m3/stm32/i2c/i2c_2.hpp>
Public Types
enum Mapping { REMAP_PB10_PB11 }
Static Public Member Functions
static void configurePins (Mapping mapping)
Configure the IO Pins for I2C2.
static void initialize (uint16_t ccrPrescaler)
Initialize I2C module.
static void reset ()
Performed a software reset of bus driver.
static bool start (uint8_t slaveAddress)
Requests bus control and generates a start condition.
static void restart (uint8_t slaveAddress)
Restarts the bus without loosing control.
static void read (uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Read a block of data.
static void write (uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write a block of data.
static void writeRead (uint8_t *data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write and read blocks of data.
static void attachDelegate (xpcc::i2c::Delegate *object)
Attach a delegate, which is called in the interrupt at the (un-)successful completion of an action (read or write) or after a restart.
static xpcc::i2c::ErrorState getErrorState ()
Check current ErrorState.
static xpcc::i2c::BusyState getBusyState ()
Check current BusyState.
static xpcc::i2c::BusState getBusState ()
Check the BusState after last operation.
static bool startWrite (uint8_t slaveAddress, uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::WRITE_STOP)
writes a block of data, if bus state allows.
static bool startRead (uint8_t slaveAddress, uint8_t *data, std::size_t size, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Read a block of data, if bus state allows.
static bool startWriteRead (uint8_t slaveAddress, uint8_t *data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param=xpcc::i2c::READ_STOP)
Write and read blocks of data, if bus state allows.
static void stop ()
Detailed Description
Author:
Georgi Grinshpun
Niklas Hauser
Definition at line 55 of file i2c_2.hpp.
Member Enumeration Documentation
enum xpcc::stm32::I2c2::Mapping
Enumerator:
REMAP_PB10_PB11
SCL mapped to PB10, SDA mapped to PB11.
Definition at line 58 of file i2c_2.hpp.
Member Function Documentation
static void xpcc::stm32::I2c2::initialize (uint16_t ccrPrescaler) [static]
Parameters:
ccrPrescaler,: I2CFrequency = STM32_APB1_FREQUENCY / (2 * ccrPrescaler)
static bool xpcc::stm32::I2c2::start (uint8_t slaveAddress) [static]
Parameters:
[in] slaveAddress Shifted 7-bit address of the slave device. LSB must be zero.
Returns:
Caller gains control if true. Call has no effect if false.
Reimplemented from xpcc::i2c::Master.
Referenced by startRead(), startWrite(), and startWriteRead().
static void xpcc::stm32::I2c2::restart (uint8_t slaveAddress) [static]
Multiple calls will result in generating only one start condition.
Parameters:
[in] slaveAddress Shifted 7-bit address of the slave device. LSB must be zero.
Reimplemented from xpcc::i2c::Master.
static void xpcc::stm32::I2c2::read (uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method only if BusState allows reading.
Parameters:
[out] *data Pointer to buffer where received data should be stored. This must remain valid during operation is in progress.
[in] size Number of bytes to be received
[in] param See description OperationParameter. Default is READ_STOP.
Reimplemented from xpcc::i2c::Master.
static void xpcc::stm32::I2c2::write (uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method if BusState allows writing.
Parameters:
data Pointer to buffer containing data to send. This must remain valid during operation is in progress.
size Number of bytes to be send
[in] param See description OperationParameter. Default is WRITE_STOP.
Reimplemented from xpcc::i2c::Master.
static void xpcc::stm32::I2c2::writeRead (uint8_t * data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [static]
Call this method if BusState allows writing.
Parameters:
data Pointer to the buffer containing data to be send and where received data should be stored. This must remain valid while the operation is in progress. The data sent will be (partially) overwritten by the data received! The Delegate will not be called after the write operation completed, but only after the receive operation completed.
writeSize Number of bytes to be send
readSize Number of bytes to be received
[in] param See description OperationParameter. Default is READ_STOP.
Reimplemented from xpcc::i2c::Master.
Referenced by startRead(), startWrite(), and startWriteRead().
static void xpcc::stm32::I2c2::attachDelegate (xpcc::i2c::Delegate * object) [static]
This allows for true asynchonous operation, multistage driver design and performance gain by premature data evaluation. The delegate gets reset after it has been called, meaning it has to be (re-)attached everytime a new action is being committed.
Parameters:
object class that inherits from Delegate
Reimplemented from xpcc::i2c::Master.
static xpcc::i2c::BusState xpcc::stm32::I2c2::getBusState () [static]
This message should only be called by owner while BusyState is occupied. In other cases returned value is not relevant.
Returns:
BusState if BusyState is occupied
Reimplemented from xpcc::i2c::Master.
static bool xpcc::stm32::I2c2::startWrite (uint8_t slaveAddress, uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::WRITE_STOP) [inline, static]
 if (start(slaveAddress)) {
       write(data, size, param);
       return true;
 }
 return false;
See also:
start()
write()
Reimplemented from xpcc::i2c::Master.
Definition at line 116 of file i2c_2.hpp.
References start(), xpcc::i2c::WRITE_RESTART, and writeRead().
static bool xpcc::stm32::I2c2::startRead (uint8_t slaveAddress, uint8_t * data, std::size_t size, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [inline, static]
 if (start(slaveAddress, xpcc::i2c::READ)) {
       read(data, size, param);
       return true;
 }
 return false;
See also:
start()
read()
Reimplemented from xpcc::i2c::Master.
Definition at line 127 of file i2c_2.hpp.
References xpcc::i2c::READ_RESTART, start(), and writeRead().
static bool xpcc::stm32::I2c2::startWriteRead (uint8_t slaveAddress, uint8_t * data, std::size_t writeSize, std::size_t readSize, xpcc::i2c::OperationParameter param = xpcc::i2c::READ_STOP) [inline, static]
 if (start(slaveAddress)) {
       writeRead(data, writeSize, readSize, param);
       return true;
 }
 return false;
See also:
start()
writeRead()
Reimplemented from xpcc::i2c::Master.
Definition at line 138 of file i2c_2.hpp.
References xpcc::i2c::READ_RESTART, start(), and writeRead().
The documentation for this class was generated from the following file:
i2c_2.hpp