xpcc: xpcc::stm32::Adc3 Class Reference
xpcc::stm32::Adc3 Class Reference
STM32Fxxx
Analog/Digital-Converter module (ADC3).
#include <xpcc/architecture/platform/cortex_m3/stm32/adc/adc_3.hpp>
Public Types
enum Channels {
PIN_A0 = 0, PIN_A1 = 1, PIN_A2 = 2, PIN_A3 = 3,
PIN_C0 = 10, PIN_C1 = 11, PIN_C2 = 12, PIN_C3 = 13,
PIN_F6 = 4, PIN_F7 = 5, PIN_F8 = 6, PIN_F9 = 7,
PIN_F10 = 8, PIN_F3 = 9, PIN_F4 = 14, PIN_F5 = 15
}
Channels, which can be used with this ADC.
enum Prescaler { PRESCALER_2 = 0b00, PRESCALER_4 = 0b01, PRESCALER_6 = 0b10, PRESCALER_8 = 0b11 }
Programmable prescaler to divide the APB2 clock frequency, which is used fot the analog circuitry (not the digital interface which is used for registers).
enum SampleTime {
CYCLES_3 = 0b000, CYCLES_15 = 0b001, CYCLES_28 = 0b010, CYCLES_56 = 0b011,
CYCLES_84 = 0b100, CYCLES_112 = 0b101, CYCLES_144 = 0b110, CYCLES_480 = 0b111
}
Sampling time of the input voltage.
enum Interrupt { END_OF_CONVERSION_REGULAR = ADC_SR_EOC, END_OF_CONVERSION_INJECTED = ADC_SR_JEOC, ANALOG_WATCHDOG = ADC_SR_AWD, OVERRUN = ADC_SR_OVR }
Possible interrupts.
Static Public Member Functions
static void initialize (Prescaler prescaler=PRESCALER_8)
Initialize and enable the A/D converter.
static void setPrescaler (const Prescaler prescaler)
Select the frequency of the clock to the ADC.
static void enableTemperatureRefVMeasurement (void)
Switch on temperature- and V_REF measurement.
static void disableTemperatureRefVMeasurement (void)
Switch on temperature- and V_REF measurement.
static void setLeftAdjustResult (const bool enable)
Change the presentation of the ADC conversion result.
static void setChannel (const Channels channel, const SampleTime sampleTime=static_cast< SampleTime >(0b000))
Analog channel selection.
static void enableFreeRunningMode (void)
Enables free running mode.
static void disableFreeRunningMode (void)
Disables free running mode.
static bool isInterruptFlagSet (const Interrupt flag)
Returns if the specified interrupt flag is set.
static void resetInterruptFlags (const Interrupt flag)
Clears the specified interrupt flag.
static void disableInterrupt (const Interrupt interrupt)
Disables the ADC Conversion Complete Interrupt.
static void enableInterrupt (const Interrupt interrupt, const uint32_t priority)
Enables the ADC Conversion Complete Interrupt.
static void shutdownAdc (void)
Turns off the ADC and its clock.
static void startConversion (void)
Start a new conversion or continuous conversions.
static bool isConversionFinished (void)
static uint16_t getValue (void)
Detailed Description
The 12-bit ADC is a successive approximation analog-to-digital converter. It has up to 18 multiplexed channels allowing it measure signals from 16 external and two internal sources. The result of the ADC is stored in a left-aligned or right-aligned 16-bit data register.
This API is designed for the internal ADCs of STM32F4XX, STM32F10X_LD, STM32F10X_LD_VL, STM32F10X_MD, STM32F10X_MD_VL, STM32F10X_HD, STM32F10X_HD_VL, STM32F10X_XL and STM32F10X_CL.
Author:
Stephan Kugelmann, David Hebbeker
Definition at line 75 of file adc_3.hpp.
Member Enumeration Documentation
enum xpcc::stm32::Adc3::Channels
You can specify the channel by using a pin-name, like PIN_C0, an internal sensor, like TEMPERATURE_SENSOR or just the plain channel number, like CHANNEL_0.
Definition at line 86 of file adc_3.hpp.
enum xpcc::stm32::Adc3::Prescaler
Enumerator:
PRESCALER_2
PCLK2 divided by 2.
PRESCALER_4
PCLK2 divided by 4.
PRESCALER_6
PCLK2 divided by 6.
PRESCALER_8
PCLK2 divided by 8.
Definition at line 170 of file adc_3.hpp.
enum xpcc::stm32::Adc3::SampleTime
Total conversion time is T_con = Sampling time + 12 cycles
Enumerator:
CYCLES_3
3 ADCCLK cycles
CYCLES_15
15 ADCCLK cycles
CYCLES_28
28 ADCCLK cycles
CYCLES_56
56 ADCCLK cycles
CYCLES_84
84 ADCCLK cycles
CYCLES_112
112 ADCCLK cycles
CYCLES_144
144 ADCCLK cycles
CYCLES_480
480 ADCCLK cycles
Definition at line 183 of file adc_3.hpp.
enum xpcc::stm32::Adc3::Interrupt
An interrupt can be produced on the end of conversion for regular and injected groups, when the analog watchdog status bit is set and when the overrun status bit is set.
Enumerator:
END_OF_CONVERSION_REGULAR
End of conversion of a regular group.
END_OF_CONVERSION_INJECTED
End of conversion of an injected group.
ANALOG_WATCHDOG
Analog watchdog status bit is set.
OVERRUN
Overrun (if data are lost)
Definition at line 213 of file adc_3.hpp.
Member Function Documentation
static void xpcc::stm32::Adc3::initialize (Prescaler prescaler = PRESCALER_8) [inline, static]
Enables the ADC clock and switches on the ADC. The ADC clock prescaler will be set as well.
The ADC clock must not exceed 14 MHz. Default is a prescaler of 8 which gives a 9 Mhz ADC clock at 72 MHz APB2 clock.
Parameters:
prescaler The prescaler specifies by which factor the APB2 clock (72 MHz) will be divided.
Definition at line 238 of file adc_3.hpp.
References setPrescaler().
static void xpcc::stm32::Adc3::setPrescaler (const Prescaler prescaler) [inline, static]
The clock is common for all the ADCs (ADC1, ADC2, ADC3) and all channels.
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Parameters:
prescaler The prescaler specifies by which factor the system clock will be divided.
Definition at line 262 of file adc_3.hpp.
Referenced by initialize().
static void xpcc::stm32::Adc3::enableTemperatureRefVMeasurement (void) [inline, static]
Definition at line 276 of file adc_3.hpp.
static void xpcc::stm32::Adc3::disableTemperatureRefVMeasurement (void) [inline, static]
Definition at line 287 of file adc_3.hpp.
static void xpcc::stm32::Adc3::setLeftAdjustResult (const bool enable) [inline, static]
Parameters:
enable Set to true to left adjust the result. Otherwise, the result is right adjusted.
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Definition at line 308 of file adc_3.hpp.
static void xpcc::stm32::Adc3::setChannel (const Channels channel, const SampleTime sampleTime = static_cast< SampleTime >(0b000)) [static]
This not for scan mode. The number of channels will be set to 1, the channel selected and the corresponding pin will be set to analog input. If the the channel is modified during a conversion, the current conversion is reset and a new start pulse is sent to the ADC to convert the new chosen channnel / group of channels.
Parameters:
channel The channel which shall be read.
sampleTime The sample time to sample the input voltage.
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
static void xpcc::stm32::Adc3::enableFreeRunningMode (void) [inline, static]
The ADC will continously start conversions and provide the most recent result in the ADC register.
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Definition at line 348 of file adc_3.hpp.
static void xpcc::stm32::Adc3::disableFreeRunningMode (void) [inline, static]
The ADC will do only one sample and stop. The result will be in the ADC register.
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Definition at line 363 of file adc_3.hpp.
static bool xpcc::stm32::Adc3::isInterruptFlagSet (const Interrupt flag) [inline, static]
Returns:
true if the flag is set
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Parameters:
flag The interrupt flag, which shall be checked.
Definition at line 377 of file adc_3.hpp.
static void xpcc::stm32::Adc3::resetInterruptFlags (const Interrupt flag) [inline, static]
Parameters:
flag The interrupt flag, which shall be cleared.
Precondition:
The ADC clock must be started and the ADC switched on with initialize().
Definition at line 392 of file adc_3.hpp.
Referenced by startConversion().
static void xpcc::stm32::Adc3::enableInterrupt (const Interrupt interrupt, const uint32_t priority) [static]
You could catch the interrupt using this example function:
for STM32F4XX:
 extern "C" void ADC_IRQHandler()
for STM32F10X:
 extern "C" void ADC1_2_IRQHandler()
Precondition:
The ADC clock must be started and the ADC switched on with initialize()
Parameters:
priority Priority to set
interrupt The interrupt, which shall be enabled. See Interrupt for available interrupts.
Note:
ADC1 and ADC2 interrupts are mapped onto the same interrupt vector. ADC3 interrupts are mapped onto a separate interrupt vector.
static void xpcc::stm32::Adc3::startConversion (void) [inline, static]
Precondition:
A ADC channel must be selected with setChannel(). When using a STM32F10x a delay of at least t_STAB after initialize() must be waited!
Postcondition:
The result can be fetched with getValue()
Attention:
When using a STM32F10x, the application should allow a delay of t_STAB between power up and start of conversion. Refer to Reference Manual (RM0008) ADC_CR2_ADON.
Definition at line 447 of file adc_3.hpp.
References ANALOG_WATCHDOG, END_OF_CONVERSION_INJECTED, END_OF_CONVERSION_REGULAR, OVERRUN, and resetInterruptFlags().
static bool xpcc::stm32::Adc3::isConversionFinished (void) [inline, static]
Returns:
If the conversion is finished.
Precondition:
A conversion should have been stared with startConversion()
Definition at line 472 of file adc_3.hpp.
static uint16_t xpcc::stm32::Adc3::getValue (void) [inline, static]
Returns:
The most recent 16bit result of the ADC conversion.
Precondition:
A conversion should have been stared with startConversion()
To have a blocking GET you might do it this way:
                while(!isConversionFinished())
                {
                    // Waiting for conversion
                }
Definition at line 490 of file adc_3.hpp.
The documentation for this class was generated from the following file:
adc_3.hpp