xpcc: xpcc::atmega::AdcInterrupt Class Reference
xpcc::atmega::AdcInterrupt Class Reference
megaAVR
ADC Interrupt module.
#include <xpcc/architecture/platform/avr/atmega/adc_interrupt.hpp>
Public Types
typedef void(* Function)()
enum Reference { REFERENCE_AREF = 0, REFERENCE_INTERNAL_AVCC = 0x40, REFERENCE_INTERNAL_1V1 = 0xc0 }
enum Prescaler {
PRESCALER_2 = 0x01, PRESCALER_4 = 0x02, PRESCALER_8 = 0x03, PRESCALER_16 = 0x04,
PRESCALER_32 = 0x05, PRESCALER_64 = 0x06, PRESCALER_128 = 0x07
}
Static Public Member Functions
static void attachConversionCompleteInterrupt (Function function=xpcc::dummy)
static bool setChannel (uint8_t channel)
Analog channel selection.
static uint8_t getChannel ()
static void setEnableAdc (bool enable)
Enables the ADC.
static void setStartConversion ()
In Single Conversion mode, this starts each conversion.
static void setAutoTriggerEnable (bool enable)
Enable auto triggering of the ADC.
static void setFreeRunningMode (bool enable)
Enables free running mode.
static bool isInterruptFlagSet ()
static void clearInterruptFlag ()
Clears the interrupt flag.
static void setInterruptEnable (bool enable)
Enables the ADC Conversion Complete Interrupt.
static void setPrescaler (Prescaler prescaler)
Set the division factor between the system clock frequency and the input clock to the ADC.
static void setAutoTriggerSource (uint8_t source)
Selects which source will trigger an ADC conversion.
static void setHighSpeedMode (bool enable)
Enable the ADC High Speed mode.
static void setCurrentSourceEnable (bool enable)
Source a 100μA current to the AREF pin.
static bool isAvddOk ()
The analog functions of the ADC are powered from the AVDD domain.
static bool isReferenceVoltageOk ()
The status of the internal generated reference voltage can be monitored through this bit.
static void setAnalogChannelChange ()
The user can force a reset of the analog blocks by setting this without requesting a different channel.
static uint16_t getDataRegister ()
static void initialize (Reference referenceVoltage, Prescaler prescaler)
Initialize and enable the A/D converter.
static void enableFreeRunningMode ()
Correctly enables Free Running Mode.
static uint16_t readChannel (uint8_t channel)
Read the value an analog channel.
static bool startConversion (uint8_t channel)
Start a new conversion.
static bool isFinished ()
Check if the conversion is finished.
static uint16_t getValue ()
the most recent 16bit result of the ADC conversion
Static Public Attributes
static Function conversionComplete
Detailed Description
This class allows you to attach functions to the ADC Conversion Complete Interrupt via function pointers. Be aware however, that this implementation is slower and requires more resources than writing the function code directly into the interrupt service routines.
See also:
AnalogSensors uses this implemenation.
Author:
Niklas Hauser
Definition at line 59 of file adc_interrupt.hpp.
Member Function Documentation
static bool xpcc::atmega::Adc::setChannel (uint8_t channel) [inline, static, inherited]
Selects which analog inputs are connected to the ADC. If this is changed during a conversion, the change will not go in effect until this conversion is complete.
Available on all ATmegas.
Definition at line 196 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::startConversion().
static uint8_t xpcc::atmega::Adc::getChannel () [inline, static, inherited]
Returns:
The analog channel connected to the ADC
Available on all ATmegas.
Definition at line 220 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setEnableAdc (bool enable) [inline, static, inherited]
Available on all ATmegas.
Definition at line 263 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::initialize().
static void xpcc::atmega::Adc::setStartConversion () [inline, static, inherited]
In Free Running mode, this starts the first conversion.
Available on all ATmegas.
Definition at line 274 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::startConversion().
static void xpcc::atmega::Adc::setAutoTriggerEnable (bool enable) [inline, static, inherited]
The ADC will start a conversion on a positive edge of the selected trigger signal.
See also:
setAutoTriggerSource
Definition at line 287 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::enableFreeRunningMode().
static void xpcc::atmega::Adc::setFreeRunningMode (bool enable) [inline, static, inherited]
The ADC will continously start conversions and provide the most recent result in the ADC register.
Definition at line 300 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::enableFreeRunningMode().
static bool xpcc::atmega::Adc::isInterruptFlagSet () [inline, static, inherited]
Returns:
true if the flag is set
Available on all ATmegas.
Definition at line 311 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::isFinished(), and xpcc::atmega::Adc::readChannel().
static void xpcc::atmega::Adc::clearInterruptFlag () [inline, static, inherited]
Available on all ATmegas.
Definition at line 321 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::startConversion().
static void xpcc::atmega::Adc::setInterruptEnable (bool enable) [inline, static, inherited]
Available on all ATmegas.
See also:
AdcInterrupt
Definition at line 333 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setAutoTriggerSource (uint8_t source) [inline, static, inherited]
A conversion will be triggered by the rising edge of the selected Interrupt Flag. Note that switching from a trigger source that is cleared to a trigger source that is set, will generate a positive edge on the trigger signal. Set to 0 to enable Free Running Mode.
Definition at line 361 of file avr/atmega/adc.hpp.
Referenced by xpcc::atmega::Adc::enableFreeRunningMode().
static void xpcc::atmega::Adc::setHighSpeedMode (bool enable) [inline, static, inherited]
Set this if you wish to convert with an ADC clock frequency higher than 200KHz. Clear this bit to reduce the power consumption of the ADC when the ADC clock frequency is lower than 200KHz.
Only Available on the M- and C-series ATmega's!
Definition at line 390 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setCurrentSourceEnable (bool enable) [inline, static, inherited]
Clear this bit to use AREF pin as Analog Reference pin.
Only Available on the M- and C-series ATmega's!
Definition at line 402 of file avr/atmega/adc.hpp.
static bool xpcc::atmega::Adc::isAvddOk () [inline, static, inherited]
AVDD is supplied from an internal voltage regulator. Enabling the ADC will power-up the AVDD domain if not already requested by another functional group of the device. This method allows the user to monitor (poll) the status of the AVDD domain.
Returns:
true indicates that AVDD has been powered-up.
Only Available on the ATmega128RFA1!
Definition at line 422 of file avr/atmega/adc.hpp.
static bool xpcc::atmega::Adc::isReferenceVoltageOk () [inline, static, inherited]
After enabling the ADC and setting the reference voltage, it will be available after a start-up delay.
Returns:
true which indicates that the internal generated reference voltage is approaching final levels.
Only Available on the ATmega128RFA1!
Definition at line 438 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::setAnalogChannelChange () [inline, static, inherited]
The analog blocks of the ADC will be reset to handle possible new voltage ranges. Such a reset phase is especially important for the gain amplifier. It could be temporarily disabled by a large step of its input common voltage leading to erroneous A/D conversion results.
Only Available on the ATmega128RFA1!
Definition at line 453 of file avr/atmega/adc.hpp.
static void xpcc::atmega::Adc::initialize (Reference referenceVoltage, Prescaler prescaler) [inline, static, inherited]
Available on all ATmegas.
Definition at line 484 of file avr/atmega/adc.hpp.
References xpcc::atmega::Adc::setEnableAdc(), and xpcc::atmega::Adc::setPrescaler().
static void xpcc::atmega::Adc::enableFreeRunningMode () [inline, static, inherited]
Available on all ATmegas.
Definition at line 499 of file avr/atmega/adc.hpp.
References xpcc::atmega::Adc::setAutoTriggerEnable(), xpcc::atmega::Adc::setAutoTriggerSource(), and xpcc::atmega::Adc::setFreeRunningMode().
static uint16_t xpcc::atmega::Adc::readChannel (uint8_t channel) [inline, static, inherited]
A normal conversion takes 13 ADC clock cycles. With a clock frequency of for example 200 kHz a conversion therefore needs 65 microseconds. This time increases with a lower frequency.
Available on all ATmegas.
Definition at line 519 of file avr/atmega/adc.hpp.
References xpcc::atmega::Adc::isInterruptFlagSet(), and xpcc::atmega::Adc::startConversion().
static bool xpcc::atmega::Adc::startConversion (uint8_t channel) [inline, static, inherited]
Available on all ATmegas.
Definition at line 536 of file avr/atmega/adc.hpp.
References xpcc::atmega::Adc::clearInterruptFlag(), xpcc::atmega::Adc::setChannel(), and xpcc::atmega::Adc::setStartConversion().
Referenced by xpcc::atmega::Adc::readChannel().
static bool xpcc::atmega::Adc::isFinished () [inline, static, inherited]
Available on all ATmegas.
Definition at line 552 of file avr/atmega/adc.hpp.
References xpcc::atmega::Adc::isInterruptFlagSet().
static uint16_t xpcc::atmega::Adc::getValue () [inline, static, inherited]
Available on all ATmegas.
Definition at line 563 of file avr/atmega/adc.hpp.
The documentation for this class was generated from the following file:
adc_interrupt.hpp