XPCC: xpcc::atxmega::AdcChannelB3 Class Reference
xpcc::atxmega::AdcChannelB3 Class Reference
Analog/Digital Converter Module
ADC Channel 3 of Module B.
#include <xpcc/architecture/platform/avr/atxmega/adc/adcb_channel3.hpp>
Static Public Member Functions
static void startSingleConversion ()
Starts one single conversion.
static void setGainFactor (adc::Gain gain=adc::GAIN_1)
static void setInputMode (adc::InputMode mode=adc::INPUTMODE_INTERNAL)
static void setPositiveInput (adc::PositiveInput input)
static void setInternalInput (adc::InternalInput input)
static void setNegativeInput (adc::NegativeInput input)
static void setNegativeInput (adc::NegativeInputWithGain input)
static void setSingleEndedInput (adc::PositiveInput input)
static void setDifferentialInput (adc::PositiveInput positiveInput, adc::NegativeInput negativeInput)
static void setDifferentialInput (adc::PositiveInput positiveInput, adc::NegativeInputWithGain negativeInput, adc::Gain gain=adc::GAIN_1)
static void setInterruptMode (adc::InterruptMode mode=adc::INTERRUPT_ON_COMPLETE)
static void setInterruptLevel (InterruptLevel level=INTERRUPT_LEVEL_OFF)
static bool isConversionComplete ()
static uint16_t getResult ()
Read the last converted analog value.
static ADC_CH_t & getChannelRegister ()
static uint16_t read ()
Read the value off the analog channel (convenience function)
static void initialize (adc::Reference reference=adc::REFERENCE_INTERNAL_VCC, adc::Prescaler prescaler=adc::PRESCALER_512, adc::Resolution resolution=adc::RESOLUTION_12BIT)
Initialize ADC module.
static void setDmaRequest (adc::DmaRequest request=adc::DMA_REQUEST_OFF)
static void startSingleConversion (adc::Channel channel)
static void flush ()
Flush the ADC pipeline.
static void enable (bool enable=true)
static void setSignedConversion (bool signedMode=true)
Set signed or unsigned conversion.
static void setFreeRunningMode (bool enable=true)
Enable free running mode as defined in setChannelSweep.
static void setResolution (adc::Resolution resolution=adc::RESOLUTION_12BIT)
left/right-adjusted 12-bit result or 8-bit result
static void setReference (adc::Reference reference=adc::REFERENCE_INTERNAL_VCC)
Set reference voltage.
static void setChannelSweep (adc::ChannelSweep sweep)
Configure channel sweep.
static void setEventChannel (adc::EventChannel channel)
static void setEventAction (adc::EventAction action=adc::EVENT_ACTION_NONE)
static void setPrescaler (adc::Prescaler prescaler=adc::PRESCALER_512)
Set prescaler.
static uint8_t getInterruptFlags (bool clear=false)
static void setCompareValue (uint16_t value)
static ADC_t & getModuleRegister ()
Detailed Description
Warning:
Every channel must either be in unsigned mode (internal or single-ended conversion) or in signed mode (differential or differential conversion with gain). It is not possible to mix these two within one ADC module!
Definition at line 59 of file adcb_channel3.hpp.
Member Function Documentation
static void xpcc::atxmega::AdcChannelB3::startSingleConversion () [inline, static]
 f_adc = f_peripheral / prescaler
 t_propagation = (1 + RES / 2 + GAIN) / f_adc
 RES = 8 or 12
 GAIN = 1 if differential mode mit gain is used, 0 otherwise
Definition at line 75 of file adcb_channel3.hpp.
Referenced by read().
static bool xpcc::atxmega::AdcChannelB3::isConversionComplete () [inline, static]
Returns:
true if the conversion finished.
Definition at line 164 of file adcb_channel3.hpp.
Referenced by read().
static uint16_t xpcc::atxmega::AdcChannelB3::read () [inline, static]
Blocks until the conversion is done.
Equivalent to:
 startSingleConversion();
 while (!isConversionComplete())
     ;
 getResult();
Definition at line 197 of file adcb_channel3.hpp.
References getResult(), isConversionComplete(), and startSingleConversion().
static void xpcc::atxmega::AdcB::initialize (adc::Reference reference = adc::REFERENCE_INTERNAL_VCC, adc::Prescaler prescaler = adc::PRESCALER_512, adc::Resolution resolution = adc::RESOLUTION_12BIT) [static, inherited]
Enables the module and loads the ADC calibration registers. Default is right adjusted 12-bit unsigned conversion mode.
static void xpcc::atxmega::AdcB::flush () [inline, static, inherited]
Starting an ADC conversion may cause an unknown delay between the software start or event and the actual conversion start since conversion of other higher priority ADC channels may be pending, or since the System clock may be much faster than the ADC Clock.
To start an ADC conversion immediately on an incoming event, it is possible to flush the ADC for all measurements, reset the ADC clock and start the conversion at the next Peripheral clock cycle, which then will also be the next ADC clock cycle.
If this is done all ongoing conversions in the ADC pipeline will be lost.
Definition at line 102 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setSignedConversion (bool signedMode = true) [inline, static, inherited]
Changing the mode to signed conversion will require the setup of two pins.
Definition at line 120 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setFreeRunningMode (bool enable = true) [inline, static, inherited]
See also:
setChannelSweep()
Definition at line 131 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setResolution (adc::Resolution resolution = adc::RESOLUTION_12BIT) [inline, static, inherited]
Default is right adjusted 12-bit mode.
Definition at line 142 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setReference (adc::Reference reference = adc::REFERENCE_INTERNAL_VCC) [inline, static, inherited]
The ADC has four possible reference voltages:
Internal 1V (REFERENCE_INTERNAL_1V)
Vcc/1.6 (REFERENCE_INTERNAL_VCC)
AREF on PORTA (REFERENCE_EXTERNAL_PORTA)
AREF on PORTB (REFERENCE_EXTERNAL_PORTB)
AVCC/2 (only on Xmega D devices)
The voltage on the AREF pins is limited to 1V < Vref < Vcc - 0.6V. For a 3.3V supply voltage this puts the upper limit on Vref to 2.7V.
In unsigned mode a small offset of 0.05*Vref is subtracted. Therefore the measurement of AGND will lead to value of about 200. This also limits the input range from AGND to 0.95*Vref.
Definition at line 166 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setChannelSweep (adc::ChannelSweep sweep) [inline, static, inherited]
Select which channels to include in free-running mode. You can choose between channel 0 only, channel 0 and 1, channel 0 to 2 or all four channels.
Care should be taken not to change any involved MUX settings when in free-running mode, as this would corrupt conversion results.
See also:
setFreeRunningMode()
Definition at line 185 of file adcb.hpp.
static void xpcc::atxmega::AdcB::setPrescaler (adc::Prescaler prescaler = adc::PRESCALER_512) [inline, static, inherited]
ADC clock frequency should be at around 62kHz for maximum resolution of internal sources.
For external measurements the frequency should be between 100kHz and 2MHz.
Definition at line 213 of file adcb.hpp.
The documentation for this class was generated from the following file:
adcb_channel3.hpp